# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawFleetClient, RawFleetClient
from .types.post_v1fleet_assignments_create_response import PostV1FleetAssignmentsCreateResponse
from .types.post_v1fleet_assignments_end_response import PostV1FleetAssignmentsEndResponse
from .types.post_v1fleet_assignments_list_request_filter_item import PostV1FleetAssignmentsListRequestFilterItem
from .types.post_v1fleet_assignments_list_request_sort_item import PostV1FleetAssignmentsListRequestSortItem
from .types.post_v1fleet_assignments_list_response import PostV1FleetAssignmentsListResponse
from .types.post_v1fleet_natura_preview_response import PostV1FleetNaturaPreviewResponse
from .types.post_v1fleet_vehicles_create_request_documents_item import PostV1FleetVehiclesCreateRequestDocumentsItem
from .types.post_v1fleet_vehicles_create_request_fuel_type import PostV1FleetVehiclesCreateRequestFuelType
from .types.post_v1fleet_vehicles_create_response import PostV1FleetVehiclesCreateResponse
from .types.post_v1fleet_vehicles_get_response import PostV1FleetVehiclesGetResponse
from .types.post_v1fleet_vehicles_list_request_filter_item import PostV1FleetVehiclesListRequestFilterItem
from .types.post_v1fleet_vehicles_list_request_sort_item import PostV1FleetVehiclesListRequestSortItem
from .types.post_v1fleet_vehicles_list_response import PostV1FleetVehiclesListResponse
from .types.post_v1fleet_vehicles_update_request_fuel_type import PostV1FleetVehiclesUpdateRequestFuelType
from .types.post_v1fleet_vehicles_update_request_status import PostV1FleetVehiclesUpdateRequestStatus
from .types.post_v1fleet_vehicles_update_response import PostV1FleetVehiclesUpdateResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FleetClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFleetClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFleetClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFleetClient
        """
        return self._raw_client

    def post_v1fleet_vehicles_create(
        self,
        *,
        plate_number: str,
        make: str,
        model: str,
        year: typing.Optional[int] = OMIT,
        vin: typing.Optional[str] = OMIT,
        fuel_type: typing.Optional[PostV1FleetVehiclesCreateRequestFuelType] = OMIT,
        acquisition_date: typing.Optional[str] = OMIT,
        market_value: typing.Optional[str] = OMIT,
        fixed_asset_id: typing.Optional[str] = OMIT,
        technical_inspection_due: typing.Optional[str] = OMIT,
        insurance_due: typing.Optional[str] = OMIT,
        notes: typing.Optional[str] = OMIT,
        documents: typing.Optional[typing.Sequence[PostV1FleetVehiclesCreateRequestDocumentsItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1FleetVehiclesCreateResponse:
        """
        Parameters
        ----------
        plate_number : str

        make : str

        model : str

        year : typing.Optional[int]

        vin : typing.Optional[str]

        fuel_type : typing.Optional[PostV1FleetVehiclesCreateRequestFuelType]

        acquisition_date : typing.Optional[str]

        market_value : typing.Optional[str]

        fixed_asset_id : typing.Optional[str]

        technical_inspection_due : typing.Optional[str]

        insurance_due : typing.Optional[str]

        notes : typing.Optional[str]

        documents : typing.Optional[typing.Sequence[PostV1FleetVehiclesCreateRequestDocumentsItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetVehiclesCreateResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.fleet.post_v1fleet_vehicles_create(
            plate_number="plateNumber",
            make="make",
            model="model",
        )
        """
        _response = self._raw_client.post_v1fleet_vehicles_create(
            plate_number=plate_number,
            make=make,
            model=model,
            year=year,
            vin=vin,
            fuel_type=fuel_type,
            acquisition_date=acquisition_date,
            market_value=market_value,
            fixed_asset_id=fixed_asset_id,
            technical_inspection_due=technical_inspection_due,
            insurance_due=insurance_due,
            notes=notes,
            documents=documents,
            request_options=request_options,
        )
        return _response.data

    def post_v1fleet_vehicles_update(
        self,
        *,
        id: str,
        plate_number: typing.Optional[str] = OMIT,
        make: typing.Optional[str] = OMIT,
        model: typing.Optional[str] = OMIT,
        year: typing.Optional[int] = OMIT,
        vin: typing.Optional[str] = OMIT,
        fuel_type: typing.Optional[PostV1FleetVehiclesUpdateRequestFuelType] = OMIT,
        acquisition_date: typing.Optional[str] = OMIT,
        market_value: typing.Optional[str] = OMIT,
        fixed_asset_id: typing.Optional[str] = OMIT,
        technical_inspection_due: typing.Optional[str] = OMIT,
        insurance_due: typing.Optional[str] = OMIT,
        status: typing.Optional[PostV1FleetVehiclesUpdateRequestStatus] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1FleetVehiclesUpdateResponse:
        """
        Parameters
        ----------
        id : str

        plate_number : typing.Optional[str]

        make : typing.Optional[str]

        model : typing.Optional[str]

        year : typing.Optional[int]

        vin : typing.Optional[str]

        fuel_type : typing.Optional[PostV1FleetVehiclesUpdateRequestFuelType]

        acquisition_date : typing.Optional[str]

        market_value : typing.Optional[str]

        fixed_asset_id : typing.Optional[str]

        technical_inspection_due : typing.Optional[str]

        insurance_due : typing.Optional[str]

        status : typing.Optional[PostV1FleetVehiclesUpdateRequestStatus]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetVehiclesUpdateResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.fleet.post_v1fleet_vehicles_update(
            id="id",
        )
        """
        _response = self._raw_client.post_v1fleet_vehicles_update(
            id=id,
            plate_number=plate_number,
            make=make,
            model=model,
            year=year,
            vin=vin,
            fuel_type=fuel_type,
            acquisition_date=acquisition_date,
            market_value=market_value,
            fixed_asset_id=fixed_asset_id,
            technical_inspection_due=technical_inspection_due,
            insurance_due=insurance_due,
            status=status,
            notes=notes,
            request_options=request_options,
        )
        return _response.data

    def post_v1fleet_vehicles_get(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1FleetVehiclesGetResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetVehiclesGetResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.fleet.post_v1fleet_vehicles_get(
            id="id",
        )
        """
        _response = self._raw_client.post_v1fleet_vehicles_get(id=id, request_options=request_options)
        return _response.data

    def post_v1fleet_vehicles_list(
        self,
        *,
        page: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        sort: typing.Optional[typing.Sequence[PostV1FleetVehiclesListRequestSortItem]] = OMIT,
        filter: typing.Optional[typing.Sequence[PostV1FleetVehiclesListRequestFilterItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1FleetVehiclesListResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[PostV1FleetVehiclesListRequestSortItem]]

        filter : typing.Optional[typing.Sequence[PostV1FleetVehiclesListRequestFilterItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetVehiclesListResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.fleet.post_v1fleet_vehicles_list()
        """
        _response = self._raw_client.post_v1fleet_vehicles_list(
            page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    def post_v1fleet_assignments_create(
        self,
        *,
        vehicle_id: str,
        employee_id: str,
        from_date: str,
        to_date: typing.Optional[str] = OMIT,
        private_use: typing.Optional[bool] = OMIT,
        employer_pays_fuel: typing.Optional[bool] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1FleetAssignmentsCreateResponse:
        """
        Parameters
        ----------
        vehicle_id : str

        employee_id : str

        from_date : str

        to_date : typing.Optional[str]

        private_use : typing.Optional[bool]

        employer_pays_fuel : typing.Optional[bool]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetAssignmentsCreateResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.fleet.post_v1fleet_assignments_create(
            vehicle_id="vehicleId",
            employee_id="employeeId",
            from_date="fromDate",
        )
        """
        _response = self._raw_client.post_v1fleet_assignments_create(
            vehicle_id=vehicle_id,
            employee_id=employee_id,
            from_date=from_date,
            to_date=to_date,
            private_use=private_use,
            employer_pays_fuel=employer_pays_fuel,
            notes=notes,
            request_options=request_options,
        )
        return _response.data

    def post_v1fleet_assignments_end(
        self, *, id: str, to_date: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1FleetAssignmentsEndResponse:
        """
        Parameters
        ----------
        id : str

        to_date : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetAssignmentsEndResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.fleet.post_v1fleet_assignments_end(
            id="id",
            to_date="toDate",
        )
        """
        _response = self._raw_client.post_v1fleet_assignments_end(
            id=id, to_date=to_date, request_options=request_options
        )
        return _response.data

    def post_v1fleet_assignments_list(
        self,
        *,
        page: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        sort: typing.Optional[typing.Sequence[PostV1FleetAssignmentsListRequestSortItem]] = OMIT,
        filter: typing.Optional[typing.Sequence[PostV1FleetAssignmentsListRequestFilterItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1FleetAssignmentsListResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[PostV1FleetAssignmentsListRequestSortItem]]

        filter : typing.Optional[typing.Sequence[PostV1FleetAssignmentsListRequestFilterItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetAssignmentsListResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.fleet.post_v1fleet_assignments_list()
        """
        _response = self._raw_client.post_v1fleet_assignments_list(
            page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    def post_v1fleet_natura_preview(
        self, *, year: int, month: int, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1FleetNaturaPreviewResponse:
        """
        Parameters
        ----------
        year : int

        month : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetNaturaPreviewResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.fleet.post_v1fleet_natura_preview(
            year=1000000,
            month=1000000,
        )
        """
        _response = self._raw_client.post_v1fleet_natura_preview(
            year=year, month=month, request_options=request_options
        )
        return _response.data


class AsyncFleetClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFleetClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFleetClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFleetClient
        """
        return self._raw_client

    async def post_v1fleet_vehicles_create(
        self,
        *,
        plate_number: str,
        make: str,
        model: str,
        year: typing.Optional[int] = OMIT,
        vin: typing.Optional[str] = OMIT,
        fuel_type: typing.Optional[PostV1FleetVehiclesCreateRequestFuelType] = OMIT,
        acquisition_date: typing.Optional[str] = OMIT,
        market_value: typing.Optional[str] = OMIT,
        fixed_asset_id: typing.Optional[str] = OMIT,
        technical_inspection_due: typing.Optional[str] = OMIT,
        insurance_due: typing.Optional[str] = OMIT,
        notes: typing.Optional[str] = OMIT,
        documents: typing.Optional[typing.Sequence[PostV1FleetVehiclesCreateRequestDocumentsItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1FleetVehiclesCreateResponse:
        """
        Parameters
        ----------
        plate_number : str

        make : str

        model : str

        year : typing.Optional[int]

        vin : typing.Optional[str]

        fuel_type : typing.Optional[PostV1FleetVehiclesCreateRequestFuelType]

        acquisition_date : typing.Optional[str]

        market_value : typing.Optional[str]

        fixed_asset_id : typing.Optional[str]

        technical_inspection_due : typing.Optional[str]

        insurance_due : typing.Optional[str]

        notes : typing.Optional[str]

        documents : typing.Optional[typing.Sequence[PostV1FleetVehiclesCreateRequestDocumentsItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetVehiclesCreateResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.fleet.post_v1fleet_vehicles_create(
                plate_number="plateNumber",
                make="make",
                model="model",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1fleet_vehicles_create(
            plate_number=plate_number,
            make=make,
            model=model,
            year=year,
            vin=vin,
            fuel_type=fuel_type,
            acquisition_date=acquisition_date,
            market_value=market_value,
            fixed_asset_id=fixed_asset_id,
            technical_inspection_due=technical_inspection_due,
            insurance_due=insurance_due,
            notes=notes,
            documents=documents,
            request_options=request_options,
        )
        return _response.data

    async def post_v1fleet_vehicles_update(
        self,
        *,
        id: str,
        plate_number: typing.Optional[str] = OMIT,
        make: typing.Optional[str] = OMIT,
        model: typing.Optional[str] = OMIT,
        year: typing.Optional[int] = OMIT,
        vin: typing.Optional[str] = OMIT,
        fuel_type: typing.Optional[PostV1FleetVehiclesUpdateRequestFuelType] = OMIT,
        acquisition_date: typing.Optional[str] = OMIT,
        market_value: typing.Optional[str] = OMIT,
        fixed_asset_id: typing.Optional[str] = OMIT,
        technical_inspection_due: typing.Optional[str] = OMIT,
        insurance_due: typing.Optional[str] = OMIT,
        status: typing.Optional[PostV1FleetVehiclesUpdateRequestStatus] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1FleetVehiclesUpdateResponse:
        """
        Parameters
        ----------
        id : str

        plate_number : typing.Optional[str]

        make : typing.Optional[str]

        model : typing.Optional[str]

        year : typing.Optional[int]

        vin : typing.Optional[str]

        fuel_type : typing.Optional[PostV1FleetVehiclesUpdateRequestFuelType]

        acquisition_date : typing.Optional[str]

        market_value : typing.Optional[str]

        fixed_asset_id : typing.Optional[str]

        technical_inspection_due : typing.Optional[str]

        insurance_due : typing.Optional[str]

        status : typing.Optional[PostV1FleetVehiclesUpdateRequestStatus]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetVehiclesUpdateResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.fleet.post_v1fleet_vehicles_update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1fleet_vehicles_update(
            id=id,
            plate_number=plate_number,
            make=make,
            model=model,
            year=year,
            vin=vin,
            fuel_type=fuel_type,
            acquisition_date=acquisition_date,
            market_value=market_value,
            fixed_asset_id=fixed_asset_id,
            technical_inspection_due=technical_inspection_due,
            insurance_due=insurance_due,
            status=status,
            notes=notes,
            request_options=request_options,
        )
        return _response.data

    async def post_v1fleet_vehicles_get(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1FleetVehiclesGetResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetVehiclesGetResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.fleet.post_v1fleet_vehicles_get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1fleet_vehicles_get(id=id, request_options=request_options)
        return _response.data

    async def post_v1fleet_vehicles_list(
        self,
        *,
        page: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        sort: typing.Optional[typing.Sequence[PostV1FleetVehiclesListRequestSortItem]] = OMIT,
        filter: typing.Optional[typing.Sequence[PostV1FleetVehiclesListRequestFilterItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1FleetVehiclesListResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[PostV1FleetVehiclesListRequestSortItem]]

        filter : typing.Optional[typing.Sequence[PostV1FleetVehiclesListRequestFilterItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetVehiclesListResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.fleet.post_v1fleet_vehicles_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1fleet_vehicles_list(
            page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    async def post_v1fleet_assignments_create(
        self,
        *,
        vehicle_id: str,
        employee_id: str,
        from_date: str,
        to_date: typing.Optional[str] = OMIT,
        private_use: typing.Optional[bool] = OMIT,
        employer_pays_fuel: typing.Optional[bool] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1FleetAssignmentsCreateResponse:
        """
        Parameters
        ----------
        vehicle_id : str

        employee_id : str

        from_date : str

        to_date : typing.Optional[str]

        private_use : typing.Optional[bool]

        employer_pays_fuel : typing.Optional[bool]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetAssignmentsCreateResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.fleet.post_v1fleet_assignments_create(
                vehicle_id="vehicleId",
                employee_id="employeeId",
                from_date="fromDate",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1fleet_assignments_create(
            vehicle_id=vehicle_id,
            employee_id=employee_id,
            from_date=from_date,
            to_date=to_date,
            private_use=private_use,
            employer_pays_fuel=employer_pays_fuel,
            notes=notes,
            request_options=request_options,
        )
        return _response.data

    async def post_v1fleet_assignments_end(
        self, *, id: str, to_date: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1FleetAssignmentsEndResponse:
        """
        Parameters
        ----------
        id : str

        to_date : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetAssignmentsEndResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.fleet.post_v1fleet_assignments_end(
                id="id",
                to_date="toDate",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1fleet_assignments_end(
            id=id, to_date=to_date, request_options=request_options
        )
        return _response.data

    async def post_v1fleet_assignments_list(
        self,
        *,
        page: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        sort: typing.Optional[typing.Sequence[PostV1FleetAssignmentsListRequestSortItem]] = OMIT,
        filter: typing.Optional[typing.Sequence[PostV1FleetAssignmentsListRequestFilterItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1FleetAssignmentsListResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[PostV1FleetAssignmentsListRequestSortItem]]

        filter : typing.Optional[typing.Sequence[PostV1FleetAssignmentsListRequestFilterItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetAssignmentsListResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.fleet.post_v1fleet_assignments_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1fleet_assignments_list(
            page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    async def post_v1fleet_natura_preview(
        self, *, year: int, month: int, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1FleetNaturaPreviewResponse:
        """
        Parameters
        ----------
        year : int

        month : int

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1FleetNaturaPreviewResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.fleet.post_v1fleet_natura_preview(
                year=1000000,
                month=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1fleet_natura_preview(
            year=year, month=month, request_options=request_options
        )
        return _response.data
