# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_v1bank_feeds_connections_get_response_accounts_item import PostV1BankFeedsConnectionsGetResponseAccountsItem
from .post_v1bank_feeds_connections_get_response_psu_type import PostV1BankFeedsConnectionsGetResponsePsuType
from .post_v1bank_feeds_connections_get_response_status import PostV1BankFeedsConnectionsGetResponseStatus


class PostV1BankFeedsConnectionsGetResponse(UniversalBaseModel):
    id: str
    provider: str
    aspsp_name: typing_extensions.Annotated[str, FieldMetadata(alias="aspspName"), pydantic.Field(alias="aspspName")]
    aspsp_country: typing_extensions.Annotated[
        str, FieldMetadata(alias="aspspCountry"), pydantic.Field(alias="aspspCountry")
    ]
    psu_type: typing_extensions.Annotated[
        PostV1BankFeedsConnectionsGetResponsePsuType, FieldMetadata(alias="psuType"), pydantic.Field(alias="psuType")
    ]
    status: PostV1BankFeedsConnectionsGetResponseStatus
    reference: str
    consent_expires_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="consentExpiresAt"), pydantic.Field(alias="consentExpiresAt")
    ] = None
    last_synced_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="lastSyncedAt"), pydantic.Field(alias="lastSyncedAt")
    ] = None
    error: typing.Optional[str] = None
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]
    updated_at: typing_extensions.Annotated[str, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")]
    accounts: typing.List[PostV1BankFeedsConnectionsGetResponseAccountsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
