# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_v1bank_feeds_connections_list_request_filter_item_op import PostV1BankFeedsConnectionsListRequestFilterItemOp
from .post_v1bank_feeds_connections_list_request_filter_item_value import (
    PostV1BankFeedsConnectionsListRequestFilterItemValue,
)


class PostV1BankFeedsConnectionsListRequestFilterItem(UniversalBaseModel):
    field: str
    op: PostV1BankFeedsConnectionsListRequestFilterItemOp
    value: PostV1BankFeedsConnectionsListRequestFilterItemValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
