# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_v1bank_feeds_banks_list_response_banks_item_psu_types_item import (
    PostV1BankFeedsBanksListResponseBanksItemPsuTypesItem,
)


class PostV1BankFeedsBanksListResponseBanksItem(UniversalBaseModel):
    name: str
    country: str
    logo_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="logoUrl"), pydantic.Field(alias="logoUrl")
    ] = None
    psu_types: typing_extensions.Annotated[
        typing.List[PostV1BankFeedsBanksListResponseBanksItemPsuTypesItem],
        FieldMetadata(alias="psuTypes"),
        pydantic.Field(alias="psuTypes"),
    ]
    max_consent_days: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="maxConsentDays"), pydantic.Field(alias="maxConsentDays")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
