# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class PostV1BankMatchRulesCreateResponse(UniversalBaseModel):
    id: str
    name: str
    provider: str
    pattern: str
    payout_id_prefix: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="payoutIdPrefix"), pydantic.Field(alias="payoutIdPrefix")
    ] = None
    bank_account_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="bankAccountId"), pydantic.Field(alias="bankAccountId")
    ] = None
    date_window_days: typing_extensions.Annotated[
        int, FieldMetadata(alias="dateWindowDays"), pydantic.Field(alias="dateWindowDays")
    ]
    is_active: typing_extensions.Annotated[bool, FieldMetadata(alias="isActive"), pydantic.Field(alias="isActive")]
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
