# This file was auto-generated by Fern from our API Definition.

import typing

PostV1SalesInvoicesUpdateRequestVatScheme = typing.Union[
    typing.Literal[
        "domestic",
        "intra_eu_b2b",
        "reverse_charge",
        "oss_union",
        "ioss",
        "marketplace_deemed",
        "export",
        "out_of_scope",
    ],
    typing.Any,
]
