# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_v1sales_acts_list_response_rows_item_status import PostV1SalesActsListResponseRowsItemStatus
from .post_v1sales_acts_list_response_rows_item_type import PostV1SalesActsListResponseRowsItemType


class PostV1SalesActsListResponseRowsItem(UniversalBaseModel):
    id: str
    partner_id: typing_extensions.Annotated[str, FieldMetadata(alias="partnerId"), pydantic.Field(alias="partnerId")]
    type: PostV1SalesActsListResponseRowsItemType
    status: PostV1SalesActsListResponseRowsItemStatus
    series: str
    full_number: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="fullNumber"), pydantic.Field(alias="fullNumber")
    ] = None
    document_date: typing_extensions.Annotated[
        str, FieldMetadata(alias="documentDate"), pydantic.Field(alias="documentDate")
    ]
    sale_invoice_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="saleInvoiceId"), pydantic.Field(alias="saleInvoiceId")
    ] = None
    transferred_by_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="transferredByName"), pydantic.Field(alias="transferredByName")
    ] = None
    transferred_by_title: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="transferredByTitle"), pydantic.Field(alias="transferredByTitle")
    ] = None
    accepted_by_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="acceptedByName"), pydantic.Field(alias="acceptedByName")
    ] = None
    accepted_by_title: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="acceptedByTitle"), pydantic.Field(alias="acceptedByTitle")
    ] = None
    notes: typing.Optional[str] = None
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]
    updated_at: typing_extensions.Annotated[str, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
