# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawPayrollClient, RawPayrollClient
from .types.post_v1payroll_calc_response import PostV1PayrollCalcResponse
from .types.post_v1payroll_departments_create_response import PostV1PayrollDepartmentsCreateResponse
from .types.post_v1payroll_departments_list_response import PostV1PayrollDepartmentsListResponse
from .types.post_v1payroll_lines_attendance_response import PostV1PayrollLinesAttendanceResponse
from .types.post_v1payroll_payments_export_response import PostV1PayrollPaymentsExportResponse
from .types.post_v1payroll_runs_approve_response import PostV1PayrollRunsApproveResponse
from .types.post_v1payroll_runs_cancel_response import PostV1PayrollRunsCancelResponse
from .types.post_v1payroll_runs_create_request_gross_overrides_item import (
    PostV1PayrollRunsCreateRequestGrossOverridesItem,
)
from .types.post_v1payroll_runs_create_request_lines_item import PostV1PayrollRunsCreateRequestLinesItem
from .types.post_v1payroll_runs_create_response import PostV1PayrollRunsCreateResponse
from .types.post_v1payroll_runs_get_response import PostV1PayrollRunsGetResponse
from .types.post_v1payroll_runs_list_request_filter_item import PostV1PayrollRunsListRequestFilterItem
from .types.post_v1payroll_runs_list_request_sort_item import PostV1PayrollRunsListRequestSortItem
from .types.post_v1payroll_runs_list_response import PostV1PayrollRunsListResponse
from .types.post_v1payroll_schedules_create_response import PostV1PayrollSchedulesCreateResponse
from .types.post_v1payroll_schedules_list_response import PostV1PayrollSchedulesListResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PayrollClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPayrollClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPayrollClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPayrollClient
        """
        return self._raw_client

    def post_v1payroll_departments_create(
        self, *, code: str, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1PayrollDepartmentsCreateResponse:
        """
        Parameters
        ----------
        code : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollDepartmentsCreateResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.payroll.post_v1payroll_departments_create(
            code="code",
            name="name",
        )
        """
        _response = self._raw_client.post_v1payroll_departments_create(
            code=code, name=name, request_options=request_options
        )
        return _response.data

    def post_v1payroll_departments_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1PayrollDepartmentsListResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollDepartmentsListResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.payroll.post_v1payroll_departments_list()
        """
        _response = self._raw_client.post_v1payroll_departments_list(request_options=request_options)
        return _response.data

    def post_v1payroll_schedules_create(
        self,
        *,
        code: str,
        name: str,
        hours_per_week: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PayrollSchedulesCreateResponse:
        """
        Parameters
        ----------
        code : str

        name : str

        hours_per_week : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollSchedulesCreateResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.payroll.post_v1payroll_schedules_create(
            code="code",
            name="name",
        )
        """
        _response = self._raw_client.post_v1payroll_schedules_create(
            code=code, name=name, hours_per_week=hours_per_week, request_options=request_options
        )
        return _response.data

    def post_v1payroll_schedules_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1PayrollSchedulesListResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollSchedulesListResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.payroll.post_v1payroll_schedules_list()
        """
        _response = self._raw_client.post_v1payroll_schedules_list(request_options=request_options)
        return _response.data

    def calculate_one_employee_payment_under_the_rules_of_the_company_country(
        self,
        *,
        taxable_base: str,
        date: str,
        apply_allowance: typing.Optional[bool] = OMIT,
        allowance_override: typing.Optional[str] = OMIT,
        pension_accumulation: typing.Optional[bool] = OMIT,
        fixed_term: typing.Optional[bool] = OMIT,
        benefit_in_kind: typing.Optional[str] = OMIT,
        options: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PayrollCalcResponse:
        """
        Parameters
        ----------
        taxable_base : str

        date : str

        apply_allowance : typing.Optional[bool]

        allowance_override : typing.Optional[str]

        pension_accumulation : typing.Optional[bool]

        fixed_term : typing.Optional[bool]

        benefit_in_kind : typing.Optional[str]

        options : typing.Optional[typing.Dict[str, str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollCalcResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.payroll.calculate_one_employee_payment_under_the_rules_of_the_company_country(
            taxable_base="taxableBase",
            date="date",
        )
        """
        _response = self._raw_client.calculate_one_employee_payment_under_the_rules_of_the_company_country(
            taxable_base=taxable_base,
            date=date,
            apply_allowance=apply_allowance,
            allowance_override=allowance_override,
            pension_accumulation=pension_accumulation,
            fixed_term=fixed_term,
            benefit_in_kind=benefit_in_kind,
            options=options,
            request_options=request_options,
        )
        return _response.data

    def post_v1payroll_runs_create(
        self,
        *,
        year: int,
        month: int,
        include_natura: typing.Optional[bool] = OMIT,
        gross_overrides: typing.Optional[typing.Sequence[PostV1PayrollRunsCreateRequestGrossOverridesItem]] = OMIT,
        lines: typing.Optional[typing.Sequence[PostV1PayrollRunsCreateRequestLinesItem]] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PayrollRunsCreateResponse:
        """
        Parameters
        ----------
        year : int

        month : int

        include_natura : typing.Optional[bool]

        gross_overrides : typing.Optional[typing.Sequence[PostV1PayrollRunsCreateRequestGrossOverridesItem]]

        lines : typing.Optional[typing.Sequence[PostV1PayrollRunsCreateRequestLinesItem]]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollRunsCreateResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.payroll.post_v1payroll_runs_create(
            year=1000000,
            month=1000000,
        )
        """
        _response = self._raw_client.post_v1payroll_runs_create(
            year=year,
            month=month,
            include_natura=include_natura,
            gross_overrides=gross_overrides,
            lines=lines,
            notes=notes,
            request_options=request_options,
        )
        return _response.data

    def post_v1payroll_runs_get(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1PayrollRunsGetResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollRunsGetResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.payroll.post_v1payroll_runs_get(
            id="id",
        )
        """
        _response = self._raw_client.post_v1payroll_runs_get(id=id, request_options=request_options)
        return _response.data

    def post_v1payroll_runs_list(
        self,
        *,
        page: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        sort: typing.Optional[typing.Sequence[PostV1PayrollRunsListRequestSortItem]] = OMIT,
        filter: typing.Optional[typing.Sequence[PostV1PayrollRunsListRequestFilterItem]] = OMIT,
        totals: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PayrollRunsListResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[PostV1PayrollRunsListRequestSortItem]]

        filter : typing.Optional[typing.Sequence[PostV1PayrollRunsListRequestFilterItem]]

        totals : typing.Optional[typing.Sequence[str]]
            Numeric fields to sum over every row matching the filter (not only the current page)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollRunsListResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.payroll.post_v1payroll_runs_list()
        """
        _response = self._raw_client.post_v1payroll_runs_list(
            page=page, page_size=page_size, sort=sort, filter=filter, totals=totals, request_options=request_options
        )
        return _response.data

    def record_the_time_a_person_worked_in_a_payroll_line(
        self,
        *,
        id: str,
        days_worked: typing.Optional[str] = OMIT,
        hours_worked: typing.Optional[str] = OMIT,
        registered_days: typing.Optional[str] = OMIT,
        average_hourly_earnings: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PayrollLinesAttendanceResponse:
        """
        The days and hours worked, the days on the register and the average hourly earnings that some countries report per employment. The Czech monthly employer report asks for all four. They can be set while the run is a draft.

        Parameters
        ----------
        id : str

        days_worked : typing.Optional[str]

        hours_worked : typing.Optional[str]

        registered_days : typing.Optional[str]

        average_hourly_earnings : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollLinesAttendanceResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.payroll.record_the_time_a_person_worked_in_a_payroll_line(
            id="id",
        )
        """
        _response = self._raw_client.record_the_time_a_person_worked_in_a_payroll_line(
            id=id,
            days_worked=days_worked,
            hours_worked=hours_worked,
            registered_days=registered_days,
            average_hourly_earnings=average_hourly_earnings,
            request_options=request_options,
        )
        return _response.data

    def post_v1payroll_runs_approve(
        self,
        *,
        id: str,
        wage_account_code: typing.Optional[str] = OMIT,
        employer_account_code: typing.Optional[str] = OMIT,
        payable_account_code: typing.Optional[str] = OMIT,
        gpm_account_code: typing.Optional[str] = OMIT,
        sodra_account_code: typing.Optional[str] = OMIT,
        employer_social_account_code: typing.Optional[str] = OMIT,
        deduction_account_code: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PayrollRunsApproveResponse:
        """
        Parameters
        ----------
        id : str

        wage_account_code : typing.Optional[str]

        employer_account_code : typing.Optional[str]

        payable_account_code : typing.Optional[str]

        gpm_account_code : typing.Optional[str]

        sodra_account_code : typing.Optional[str]

        employer_social_account_code : typing.Optional[str]

        deduction_account_code : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollRunsApproveResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.payroll.post_v1payroll_runs_approve(
            id="id",
        )
        """
        _response = self._raw_client.post_v1payroll_runs_approve(
            id=id,
            wage_account_code=wage_account_code,
            employer_account_code=employer_account_code,
            payable_account_code=payable_account_code,
            gpm_account_code=gpm_account_code,
            sodra_account_code=sodra_account_code,
            employer_social_account_code=employer_social_account_code,
            deduction_account_code=deduction_account_code,
            request_options=request_options,
        )
        return _response.data

    def post_v1payroll_runs_cancel(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1PayrollRunsCancelResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollRunsCancelResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.payroll.post_v1payroll_runs_cancel(
            id="id",
        )
        """
        _response = self._raw_client.post_v1payroll_runs_cancel(id=id, request_options=request_options)
        return _response.data

    def post_v1payroll_payments_export(
        self,
        *,
        run_id: str,
        bank_account_id: str,
        execution_date: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PayrollPaymentsExportResponse:
        """
        Parameters
        ----------
        run_id : str

        bank_account_id : str

        execution_date : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollPaymentsExportResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.payroll.post_v1payroll_payments_export(
            run_id="runId",
            bank_account_id="bankAccountId",
        )
        """
        _response = self._raw_client.post_v1payroll_payments_export(
            run_id=run_id,
            bank_account_id=bank_account_id,
            execution_date=execution_date,
            request_options=request_options,
        )
        return _response.data


class AsyncPayrollClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPayrollClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPayrollClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPayrollClient
        """
        return self._raw_client

    async def post_v1payroll_departments_create(
        self, *, code: str, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1PayrollDepartmentsCreateResponse:
        """
        Parameters
        ----------
        code : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollDepartmentsCreateResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payroll.post_v1payroll_departments_create(
                code="code",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1payroll_departments_create(
            code=code, name=name, request_options=request_options
        )
        return _response.data

    async def post_v1payroll_departments_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1PayrollDepartmentsListResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollDepartmentsListResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payroll.post_v1payroll_departments_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1payroll_departments_list(request_options=request_options)
        return _response.data

    async def post_v1payroll_schedules_create(
        self,
        *,
        code: str,
        name: str,
        hours_per_week: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PayrollSchedulesCreateResponse:
        """
        Parameters
        ----------
        code : str

        name : str

        hours_per_week : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollSchedulesCreateResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payroll.post_v1payroll_schedules_create(
                code="code",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1payroll_schedules_create(
            code=code, name=name, hours_per_week=hours_per_week, request_options=request_options
        )
        return _response.data

    async def post_v1payroll_schedules_list(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1PayrollSchedulesListResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollSchedulesListResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payroll.post_v1payroll_schedules_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1payroll_schedules_list(request_options=request_options)
        return _response.data

    async def calculate_one_employee_payment_under_the_rules_of_the_company_country(
        self,
        *,
        taxable_base: str,
        date: str,
        apply_allowance: typing.Optional[bool] = OMIT,
        allowance_override: typing.Optional[str] = OMIT,
        pension_accumulation: typing.Optional[bool] = OMIT,
        fixed_term: typing.Optional[bool] = OMIT,
        benefit_in_kind: typing.Optional[str] = OMIT,
        options: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PayrollCalcResponse:
        """
        Parameters
        ----------
        taxable_base : str

        date : str

        apply_allowance : typing.Optional[bool]

        allowance_override : typing.Optional[str]

        pension_accumulation : typing.Optional[bool]

        fixed_term : typing.Optional[bool]

        benefit_in_kind : typing.Optional[str]

        options : typing.Optional[typing.Dict[str, str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollCalcResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payroll.calculate_one_employee_payment_under_the_rules_of_the_company_country(
                taxable_base="taxableBase",
                date="date",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.calculate_one_employee_payment_under_the_rules_of_the_company_country(
            taxable_base=taxable_base,
            date=date,
            apply_allowance=apply_allowance,
            allowance_override=allowance_override,
            pension_accumulation=pension_accumulation,
            fixed_term=fixed_term,
            benefit_in_kind=benefit_in_kind,
            options=options,
            request_options=request_options,
        )
        return _response.data

    async def post_v1payroll_runs_create(
        self,
        *,
        year: int,
        month: int,
        include_natura: typing.Optional[bool] = OMIT,
        gross_overrides: typing.Optional[typing.Sequence[PostV1PayrollRunsCreateRequestGrossOverridesItem]] = OMIT,
        lines: typing.Optional[typing.Sequence[PostV1PayrollRunsCreateRequestLinesItem]] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PayrollRunsCreateResponse:
        """
        Parameters
        ----------
        year : int

        month : int

        include_natura : typing.Optional[bool]

        gross_overrides : typing.Optional[typing.Sequence[PostV1PayrollRunsCreateRequestGrossOverridesItem]]

        lines : typing.Optional[typing.Sequence[PostV1PayrollRunsCreateRequestLinesItem]]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollRunsCreateResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payroll.post_v1payroll_runs_create(
                year=1000000,
                month=1000000,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1payroll_runs_create(
            year=year,
            month=month,
            include_natura=include_natura,
            gross_overrides=gross_overrides,
            lines=lines,
            notes=notes,
            request_options=request_options,
        )
        return _response.data

    async def post_v1payroll_runs_get(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1PayrollRunsGetResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollRunsGetResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payroll.post_v1payroll_runs_get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1payroll_runs_get(id=id, request_options=request_options)
        return _response.data

    async def post_v1payroll_runs_list(
        self,
        *,
        page: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        sort: typing.Optional[typing.Sequence[PostV1PayrollRunsListRequestSortItem]] = OMIT,
        filter: typing.Optional[typing.Sequence[PostV1PayrollRunsListRequestFilterItem]] = OMIT,
        totals: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PayrollRunsListResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[PostV1PayrollRunsListRequestSortItem]]

        filter : typing.Optional[typing.Sequence[PostV1PayrollRunsListRequestFilterItem]]

        totals : typing.Optional[typing.Sequence[str]]
            Numeric fields to sum over every row matching the filter (not only the current page)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollRunsListResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payroll.post_v1payroll_runs_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1payroll_runs_list(
            page=page, page_size=page_size, sort=sort, filter=filter, totals=totals, request_options=request_options
        )
        return _response.data

    async def record_the_time_a_person_worked_in_a_payroll_line(
        self,
        *,
        id: str,
        days_worked: typing.Optional[str] = OMIT,
        hours_worked: typing.Optional[str] = OMIT,
        registered_days: typing.Optional[str] = OMIT,
        average_hourly_earnings: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PayrollLinesAttendanceResponse:
        """
        The days and hours worked, the days on the register and the average hourly earnings that some countries report per employment. The Czech monthly employer report asks for all four. They can be set while the run is a draft.

        Parameters
        ----------
        id : str

        days_worked : typing.Optional[str]

        hours_worked : typing.Optional[str]

        registered_days : typing.Optional[str]

        average_hourly_earnings : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollLinesAttendanceResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payroll.record_the_time_a_person_worked_in_a_payroll_line(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.record_the_time_a_person_worked_in_a_payroll_line(
            id=id,
            days_worked=days_worked,
            hours_worked=hours_worked,
            registered_days=registered_days,
            average_hourly_earnings=average_hourly_earnings,
            request_options=request_options,
        )
        return _response.data

    async def post_v1payroll_runs_approve(
        self,
        *,
        id: str,
        wage_account_code: typing.Optional[str] = OMIT,
        employer_account_code: typing.Optional[str] = OMIT,
        payable_account_code: typing.Optional[str] = OMIT,
        gpm_account_code: typing.Optional[str] = OMIT,
        sodra_account_code: typing.Optional[str] = OMIT,
        employer_social_account_code: typing.Optional[str] = OMIT,
        deduction_account_code: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PayrollRunsApproveResponse:
        """
        Parameters
        ----------
        id : str

        wage_account_code : typing.Optional[str]

        employer_account_code : typing.Optional[str]

        payable_account_code : typing.Optional[str]

        gpm_account_code : typing.Optional[str]

        sodra_account_code : typing.Optional[str]

        employer_social_account_code : typing.Optional[str]

        deduction_account_code : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollRunsApproveResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payroll.post_v1payroll_runs_approve(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1payroll_runs_approve(
            id=id,
            wage_account_code=wage_account_code,
            employer_account_code=employer_account_code,
            payable_account_code=payable_account_code,
            gpm_account_code=gpm_account_code,
            sodra_account_code=sodra_account_code,
            employer_social_account_code=employer_social_account_code,
            deduction_account_code=deduction_account_code,
            request_options=request_options,
        )
        return _response.data

    async def post_v1payroll_runs_cancel(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1PayrollRunsCancelResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollRunsCancelResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payroll.post_v1payroll_runs_cancel(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1payroll_runs_cancel(id=id, request_options=request_options)
        return _response.data

    async def post_v1payroll_payments_export(
        self,
        *,
        run_id: str,
        bank_account_id: str,
        execution_date: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PayrollPaymentsExportResponse:
        """
        Parameters
        ----------
        run_id : str

        bank_account_id : str

        execution_date : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PayrollPaymentsExportResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payroll.post_v1payroll_payments_export(
                run_id="runId",
                bank_account_id="bankAccountId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1payroll_payments_export(
            run_id=run_id,
            bank_account_id=bank_account_id,
            execution_date=execution_date,
            request_options=request_options,
        )
        return _response.data
