# This file was auto-generated by Fern from our API Definition.

import typing

from .currencies_list_reference_request_filter_item_value_three_item import (
    CurrenciesListReferenceRequestFilterItemValueThreeItem,
)

CurrenciesListReferenceRequestFilterItemValue = typing.Union[
    str, float, bool, typing.List[CurrenciesListReferenceRequestFilterItemValueThreeItem]
]
