# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .eu_vat_rates_list_reference_response_rows_item import EuVatRatesListReferenceResponseRowsItem


class EuVatRatesListReferenceResponse(UniversalBaseModel):
    notice: str
    rows: typing.List[EuVatRatesListReferenceResponseRowsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
