# This file was auto-generated by Fern from our API Definition.

import typing

from .units_list_reference_request_filter_item_value_three_item import UnitsListReferenceRequestFilterItemValueThreeItem

UnitsListReferenceRequestFilterItemValue = typing.Union[
    str, float, bool, typing.List[UnitsListReferenceRequestFilterItemValueThreeItem]
]
