# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .deferrals_list_purchases_request_filter_item_op import DeferralsListPurchasesRequestFilterItemOp
from .deferrals_list_purchases_request_filter_item_value import DeferralsListPurchasesRequestFilterItemValue


class DeferralsListPurchasesRequestFilterItem(UniversalBaseModel):
    field: str
    op: DeferralsListPurchasesRequestFilterItemOp
    value: DeferralsListPurchasesRequestFilterItemValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
