# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class PostV1PurchasesReceiptsCreateRequestLinesItem(UniversalBaseModel):
    order_line_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="orderLineId"), pydantic.Field(alias="orderLineId")
    ]
    quantity: str
    lot_number: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="lotNumber"), pydantic.Field(alias="lotNumber")
    ] = None
    expiry_date: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="expiryDate"), pydantic.Field(alias="expiryDate")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
