# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_v1purchases_orders_list_request_sort_item_dir import PostV1PurchasesOrdersListRequestSortItemDir


class PostV1PurchasesOrdersListRequestSortItem(UniversalBaseModel):
    field: str
    dir: typing.Optional[PostV1PurchasesOrdersListRequestSortItemDir] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
