# This file was auto-generated by Fern from our API Definition.

import typing

PostV1PurchasesInvoicesCreateResponsePaymentStatus = typing.Union[
    typing.Literal["unpaid", "partial", "paid"], typing.Any
]
