# This file was auto-generated by Fern from our API Definition.

import typing

from .post_v1cash_orders_list_request_filter_item_value_three_item import (
    PostV1CashOrdersListRequestFilterItemValueThreeItem,
)

PostV1CashOrdersListRequestFilterItemValue = typing.Union[
    str, float, bool, typing.List[PostV1CashOrdersListRequestFilterItemValueThreeItem]
]
