# This file was auto-generated by Fern from our API Definition.

import typing

DeliveriesListWebhooksResponseRowsItemStatus = typing.Union[
    typing.Literal["pending", "delivered", "failed"], typing.Any
]
