# This file was auto-generated by Fern from our API Definition.

import typing

FinancialStatementsReportsRequestCategory = typing.Union[
    typing.Literal["micro", "small", "medium", "large"], typing.Any
]
