# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class PostV1ReportsStockAgingResponseRowsItem(UniversalBaseModel):
    item_id: typing_extensions.Annotated[str, FieldMetadata(alias="itemId"), pydantic.Field(alias="itemId")]
    item_name: typing_extensions.Annotated[str, FieldMetadata(alias="itemName"), pydantic.Field(alias="itemName")]
    warehouse_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="warehouseId"), pydantic.Field(alias="warehouseId")
    ]
    d0to30qty: typing_extensions.Annotated[str, FieldMetadata(alias="d0to30Qty"), pydantic.Field(alias="d0to30Qty")]
    d0to30value: typing_extensions.Annotated[
        str, FieldMetadata(alias="d0to30Value"), pydantic.Field(alias="d0to30Value")
    ]
    d31to60qty: typing_extensions.Annotated[str, FieldMetadata(alias="d31to60Qty"), pydantic.Field(alias="d31to60Qty")]
    d31to60value: typing_extensions.Annotated[
        str, FieldMetadata(alias="d31to60Value"), pydantic.Field(alias="d31to60Value")
    ]
    d61to90qty: typing_extensions.Annotated[str, FieldMetadata(alias="d61to90Qty"), pydantic.Field(alias="d61to90Qty")]
    d61to90value: typing_extensions.Annotated[
        str, FieldMetadata(alias="d61to90Value"), pydantic.Field(alias="d61to90Value")
    ]
    over90qty: typing_extensions.Annotated[str, FieldMetadata(alias="over90Qty"), pydantic.Field(alias="over90Qty")]
    over90value: typing_extensions.Annotated[
        str, FieldMetadata(alias="over90Value"), pydantic.Field(alias="over90Value")
    ]
    total_qty: typing_extensions.Annotated[str, FieldMetadata(alias="totalQty"), pydantic.Field(alias="totalQty")]
    total_value: typing_extensions.Annotated[str, FieldMetadata(alias="totalValue"), pydantic.Field(alias="totalValue")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
