# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class PostV1ReportsSizeCategoryResponseCriteria(UniversalBaseModel):
    total_assets: typing_extensions.Annotated[
        float, FieldMetadata(alias="totalAssets"), pydantic.Field(alias="totalAssets")
    ]
    net_turnover: typing_extensions.Annotated[
        float, FieldMetadata(alias="netTurnover"), pydantic.Field(alias="netTurnover")
    ]
    avg_employees: typing_extensions.Annotated[
        int, FieldMetadata(alias="avgEmployees"), pydantic.Field(alias="avgEmployees")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
