# This file was auto-generated by Fern from our API Definition.

import typing

PostV1SalesInvoicesLockResponseType = typing.Union[
    typing.Literal["invoice", "credit_note", "proforma", "advance"], typing.Any
]
