# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_v1sales_invoices_update_request_lines_item_recognition_method import (
    PostV1SalesInvoicesUpdateRequestLinesItemRecognitionMethod,
)
from .post_v1sales_invoices_update_request_lines_item_recognition_milestones_item import (
    PostV1SalesInvoicesUpdateRequestLinesItemRecognitionMilestonesItem,
)


class PostV1SalesInvoicesUpdateRequestLinesItemRecognition(UniversalBaseModel):
    method: typing.Optional[PostV1SalesInvoicesUpdateRequestLinesItemRecognitionMethod] = None
    start_date: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="startDate"), pydantic.Field(alias="startDate")
    ] = None
    end_date: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="endDate"), pydantic.Field(alias="endDate")
    ] = None
    milestones: typing.Optional[typing.List[PostV1SalesInvoicesUpdateRequestLinesItemRecognitionMilestonesItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
