# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_v1sales_recognition_runs_list_response_rows_item_trigger import (
    PostV1SalesRecognitionRunsListResponseRowsItemTrigger,
)


class PostV1SalesRecognitionRunsListResponseRowsItem(UniversalBaseModel):
    id: str
    run_date: typing_extensions.Annotated[str, FieldMetadata(alias="runDate"), pydantic.Field(alias="runDate")]
    trigger: PostV1SalesRecognitionRunsListResponseRowsItemTrigger
    schedule_count: typing_extensions.Annotated[
        int, FieldMetadata(alias="scheduleCount"), pydantic.Field(alias="scheduleCount")
    ]
    total_amount: typing_extensions.Annotated[
        str, FieldMetadata(alias="totalAmount"), pydantic.Field(alias="totalAmount")
    ]
    journal_transaction_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="journalTransactionId"), pydantic.Field(alias="journalTransactionId")
    ]
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
