# This file was auto-generated by Fern from our API Definition.

import typing

from .recognition_schedules_list_sales_request_filter_item_value_three_item import (
    RecognitionSchedulesListSalesRequestFilterItemValueThreeItem,
)

RecognitionSchedulesListSalesRequestFilterItemValue = typing.Union[
    str, float, bool, typing.List[RecognitionSchedulesListSalesRequestFilterItemValueThreeItem]
]
