# This file was auto-generated by Fern from our API Definition.

import typing

PostV1BankTransactionsMatchRequestDocumentType = typing.Union[
    typing.Literal["sale_invoice", "purchase_invoice"], typing.Any
]
