# This file was auto-generated by Fern from our API Definition.

import typing

from .assignments_list_fleet_request_filter_item_value_three_item import (
    AssignmentsListFleetRequestFilterItemValueThreeItem,
)

AssignmentsListFleetRequestFilterItemValue = typing.Union[
    str, float, bool, typing.List[AssignmentsListFleetRequestFilterItemValueThreeItem]
]
