# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_v1fleet_vehicles_list_request_filter_item_op import PostV1FleetVehiclesListRequestFilterItemOp
from .post_v1fleet_vehicles_list_request_filter_item_value import PostV1FleetVehiclesListRequestFilterItemValue


class PostV1FleetVehiclesListRequestFilterItem(UniversalBaseModel):
    field: str
    op: PostV1FleetVehiclesListRequestFilterItemOp
    value: PostV1FleetVehiclesListRequestFilterItemValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
