# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawPeppolClient, RawPeppolClient
from .types.participants_lookup_peppol_response import ParticipantsLookupPeppolResponse
from .types.webhooks_peppol_request_provider import WebhooksPeppolRequestProvider
from .types.webhooks_peppol_response import WebhooksPeppolResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PeppolClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPeppolClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPeppolClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPeppolClient
        """
        return self._raw_client

    def participants_lookup(
        self,
        *,
        partner_id: typing.Optional[str] = OMIT,
        participant_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ParticipantsLookupPeppolResponse:
        """
        Look a receiver up on the Peppol network (SML and SMP) and say which Peppol BIS Billing 3.0 documents it accepts. Give `partnerId` to look up a partner by its Peppol ID, VAT code or registration code, or `participantId` as "<scheme>:<identifier>". Works without an access point.

        Parameters
        ----------
        partner_id : typing.Optional[str]

        participant_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ParticipantsLookupPeppolResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.peppol.participants_lookup()
        """
        _response = self._raw_client.participants_lookup(
            partner_id=partner_id, participant_id=participant_id, request_options=request_options
        )
        return _response.data

    def webhooks(
        self,
        provider: WebhooksPeppolRequestProvider,
        company_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhooksPeppolResponse:
        """
        Parameters
        ----------
        provider : WebhooksPeppolRequestProvider

        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhooksPeppolResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.peppol.webhooks(
            provider="recommand",
            company_id="companyId",
        )
        """
        _response = self._raw_client.webhooks(provider, company_id, request_options=request_options)
        return _response.data


class AsyncPeppolClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPeppolClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPeppolClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPeppolClient
        """
        return self._raw_client

    async def participants_lookup(
        self,
        *,
        partner_id: typing.Optional[str] = OMIT,
        participant_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ParticipantsLookupPeppolResponse:
        """
        Look a receiver up on the Peppol network (SML and SMP) and say which Peppol BIS Billing 3.0 documents it accepts. Give `partnerId` to look up a partner by its Peppol ID, VAT code or registration code, or `participantId` as "<scheme>:<identifier>". Works without an access point.

        Parameters
        ----------
        partner_id : typing.Optional[str]

        participant_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ParticipantsLookupPeppolResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.peppol.participants_lookup()


        asyncio.run(main())
        """
        _response = await self._raw_client.participants_lookup(
            partner_id=partner_id, participant_id=participant_id, request_options=request_options
        )
        return _response.data

    async def webhooks(
        self,
        provider: WebhooksPeppolRequestProvider,
        company_id: str,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> WebhooksPeppolResponse:
        """
        Parameters
        ----------
        provider : WebhooksPeppolRequestProvider

        company_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhooksPeppolResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.peppol.webhooks(
                provider="recommand",
                company_id="companyId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.webhooks(provider, company_id, request_options=request_options)
        return _response.data
