# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_v1ledger_owners_create_response_address import PostV1LedgerOwnersCreateResponseAddress


class PostV1LedgerOwnersCreateResponse(UniversalBaseModel):
    id: str
    name: str
    code: typing.Optional[str] = None
    equity_account_code: typing_extensions.Annotated[
        str, FieldMetadata(alias="equityAccountCode"), pydantic.Field(alias="equityAccountCode")
    ]
    shares_quantity: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="sharesQuantity"), pydantic.Field(alias="sharesQuantity")
    ] = None
    shares_amount: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="sharesAmount"), pydantic.Field(alias="sharesAmount")
    ] = None
    shares_type: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="sharesType"), pydantic.Field(alias="sharesType")
    ] = None
    shares_acquisition_date: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="sharesAcquisitionDate"),
        pydantic.Field(alias="sharesAcquisitionDate"),
    ] = None
    address: typing.Optional[PostV1LedgerOwnersCreateResponseAddress] = None
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
