# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_v1assets_assets_modernize_response_documents_item import PostV1AssetsAssetsModernizeResponseDocumentsItem
from .post_v1assets_assets_modernize_response_status import PostV1AssetsAssetsModernizeResponseStatus


class PostV1AssetsAssetsModernizeResponse(UniversalBaseModel):
    id: str
    group_id: typing_extensions.Annotated[str, FieldMetadata(alias="groupId"), pydantic.Field(alias="groupId")]
    code: str
    name: str
    acquisition_date: typing_extensions.Annotated[
        str, FieldMetadata(alias="acquisitionDate"), pydantic.Field(alias="acquisitionDate")
    ]
    depreciation_start_date: typing_extensions.Annotated[
        str, FieldMetadata(alias="depreciationStartDate"), pydantic.Field(alias="depreciationStartDate")
    ]
    acquisition_cost: typing_extensions.Annotated[
        str, FieldMetadata(alias="acquisitionCost"), pydantic.Field(alias="acquisitionCost")
    ]
    salvage_value: typing_extensions.Annotated[
        str, FieldMetadata(alias="salvageValue"), pydantic.Field(alias="salvageValue")
    ]
    useful_life_months: typing_extensions.Annotated[
        int, FieldMetadata(alias="usefulLifeMonths"), pydantic.Field(alias="usefulLifeMonths")
    ]
    total_cost: typing_extensions.Annotated[str, FieldMetadata(alias="totalCost"), pydantic.Field(alias="totalCost")]
    accumulated_depreciation: typing_extensions.Annotated[
        str, FieldMetadata(alias="accumulatedDepreciation"), pydantic.Field(alias="accumulatedDepreciation")
    ]
    net_book_value: typing_extensions.Annotated[
        str, FieldMetadata(alias="netBookValue"), pydantic.Field(alias="netBookValue")
    ]
    depreciated_months: typing_extensions.Annotated[
        int, FieldMetadata(alias="depreciatedMonths"), pydantic.Field(alias="depreciatedMonths")
    ]
    total_life_months: typing_extensions.Annotated[
        int, FieldMetadata(alias="totalLifeMonths"), pydantic.Field(alias="totalLifeMonths")
    ]
    status: PostV1AssetsAssetsModernizeResponseStatus
    notes: typing.Optional[str] = None
    documents: typing.Optional[typing.List[PostV1AssetsAssetsModernizeResponseDocumentsItem]] = None
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
