# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_v1assets_assets_input_vat_request_input_vat_use_changes_item_reason import (
    PostV1AssetsAssetsInputVatRequestInputVatUseChangesItemReason,
)


class PostV1AssetsAssetsInputVatRequestInputVatUseChangesItem(UniversalBaseModel):
    year: int
    percent: str
    reason: PostV1AssetsAssetsInputVatRequestInputVatUseChangesItemReason

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
