# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_v1assets_assets_list_response_rows_item_input_vat_use_changes_item_reason import (
    PostV1AssetsAssetsListResponseRowsItemInputVatUseChangesItemReason,
)


class PostV1AssetsAssetsListResponseRowsItemInputVatUseChangesItem(UniversalBaseModel):
    year: int
    percent: str
    reason: PostV1AssetsAssetsListResponseRowsItemInputVatUseChangesItemReason

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
