# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawPurchasesClient, RawPurchasesClient
from .types.post_v1purchases_invoices_create_request_lines_item import PostV1PurchasesInvoicesCreateRequestLinesItem
from .types.post_v1purchases_invoices_create_request_type import PostV1PurchasesInvoicesCreateRequestType
from .types.post_v1purchases_invoices_create_response import PostV1PurchasesInvoicesCreateResponse
from .types.post_v1purchases_invoices_delete_response import PostV1PurchasesInvoicesDeleteResponse
from .types.post_v1purchases_invoices_get_response import PostV1PurchasesInvoicesGetResponse
from .types.post_v1purchases_invoices_list_request_filter_item import PostV1PurchasesInvoicesListRequestFilterItem
from .types.post_v1purchases_invoices_list_request_sort_item import PostV1PurchasesInvoicesListRequestSortItem
from .types.post_v1purchases_invoices_list_response import PostV1PurchasesInvoicesListResponse
from .types.post_v1purchases_invoices_register_response import PostV1PurchasesInvoicesRegisterResponse
from .types.post_v1purchases_invoices_update_request_lines_item import PostV1PurchasesInvoicesUpdateRequestLinesItem
from .types.post_v1purchases_invoices_update_response import PostV1PurchasesInvoicesUpdateResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PurchasesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPurchasesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPurchasesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPurchasesClient
        """
        return self._raw_client

    def post_v1purchases_invoices_create(
        self,
        *,
        partner_id: str,
        document_number: str,
        document_date: str,
        lines: typing.Sequence[PostV1PurchasesInvoicesCreateRequestLinesItem],
        type: typing.Optional[PostV1PurchasesInvoicesCreateRequestType] = OMIT,
        due_date: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        credited_invoice_id: typing.Optional[str] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PurchasesInvoicesCreateResponse:
        """
        Parameters
        ----------
        partner_id : str

        document_number : str

        document_date : str

        lines : typing.Sequence[PostV1PurchasesInvoicesCreateRequestLinesItem]

        type : typing.Optional[PostV1PurchasesInvoicesCreateRequestType]

        due_date : typing.Optional[str]

        currency : typing.Optional[str]

        credited_invoice_id : typing.Optional[str]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PurchasesInvoicesCreateResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet
        from nordlet.purchases import PostV1PurchasesInvoicesCreateRequestLinesItem

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.purchases.post_v1purchases_invoices_create(
            partner_id="partnerId",
            document_number="documentNumber",
            document_date="documentDate",
            lines=[PostV1PurchasesInvoicesCreateRequestLinesItem()],
        )
        """
        _response = self._raw_client.post_v1purchases_invoices_create(
            partner_id=partner_id,
            document_number=document_number,
            document_date=document_date,
            lines=lines,
            type=type,
            due_date=due_date,
            currency=currency,
            credited_invoice_id=credited_invoice_id,
            notes=notes,
            request_options=request_options,
        )
        return _response.data

    def post_v1purchases_invoices_get(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1PurchasesInvoicesGetResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PurchasesInvoicesGetResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.purchases.post_v1purchases_invoices_get(
            id="id",
        )
        """
        _response = self._raw_client.post_v1purchases_invoices_get(id=id, request_options=request_options)
        return _response.data

    def post_v1purchases_invoices_update(
        self,
        *,
        id: str,
        partner_id: typing.Optional[str] = OMIT,
        document_number: typing.Optional[str] = OMIT,
        document_date: typing.Optional[str] = OMIT,
        due_date: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        notes: typing.Optional[str] = OMIT,
        lines: typing.Optional[typing.Sequence[PostV1PurchasesInvoicesUpdateRequestLinesItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PurchasesInvoicesUpdateResponse:
        """
        Parameters
        ----------
        id : str

        partner_id : typing.Optional[str]

        document_number : typing.Optional[str]

        document_date : typing.Optional[str]

        due_date : typing.Optional[str]

        currency : typing.Optional[str]

        notes : typing.Optional[str]

        lines : typing.Optional[typing.Sequence[PostV1PurchasesInvoicesUpdateRequestLinesItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PurchasesInvoicesUpdateResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.purchases.post_v1purchases_invoices_update(
            id="id",
        )
        """
        _response = self._raw_client.post_v1purchases_invoices_update(
            id=id,
            partner_id=partner_id,
            document_number=document_number,
            document_date=document_date,
            due_date=due_date,
            currency=currency,
            notes=notes,
            lines=lines,
            request_options=request_options,
        )
        return _response.data

    def post_v1purchases_invoices_delete(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1PurchasesInvoicesDeleteResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PurchasesInvoicesDeleteResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.purchases.post_v1purchases_invoices_delete(
            id="id",
        )
        """
        _response = self._raw_client.post_v1purchases_invoices_delete(id=id, request_options=request_options)
        return _response.data

    def post_v1purchases_invoices_register(
        self,
        *,
        id: str,
        registration_date: typing.Optional[str] = OMIT,
        warehouse_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PurchasesInvoicesRegisterResponse:
        """
        Parameters
        ----------
        id : str

        registration_date : typing.Optional[str]

        warehouse_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PurchasesInvoicesRegisterResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.purchases.post_v1purchases_invoices_register(
            id="id",
        )
        """
        _response = self._raw_client.post_v1purchases_invoices_register(
            id=id, registration_date=registration_date, warehouse_id=warehouse_id, request_options=request_options
        )
        return _response.data

    def post_v1purchases_invoices_list(
        self,
        *,
        page: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        sort: typing.Optional[typing.Sequence[PostV1PurchasesInvoicesListRequestSortItem]] = OMIT,
        filter: typing.Optional[typing.Sequence[PostV1PurchasesInvoicesListRequestFilterItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PurchasesInvoicesListResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[PostV1PurchasesInvoicesListRequestSortItem]]

        filter : typing.Optional[typing.Sequence[PostV1PurchasesInvoicesListRequestFilterItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PurchasesInvoicesListResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.purchases.post_v1purchases_invoices_list()
        """
        _response = self._raw_client.post_v1purchases_invoices_list(
            page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data


class AsyncPurchasesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPurchasesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPurchasesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPurchasesClient
        """
        return self._raw_client

    async def post_v1purchases_invoices_create(
        self,
        *,
        partner_id: str,
        document_number: str,
        document_date: str,
        lines: typing.Sequence[PostV1PurchasesInvoicesCreateRequestLinesItem],
        type: typing.Optional[PostV1PurchasesInvoicesCreateRequestType] = OMIT,
        due_date: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        credited_invoice_id: typing.Optional[str] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PurchasesInvoicesCreateResponse:
        """
        Parameters
        ----------
        partner_id : str

        document_number : str

        document_date : str

        lines : typing.Sequence[PostV1PurchasesInvoicesCreateRequestLinesItem]

        type : typing.Optional[PostV1PurchasesInvoicesCreateRequestType]

        due_date : typing.Optional[str]

        currency : typing.Optional[str]

        credited_invoice_id : typing.Optional[str]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PurchasesInvoicesCreateResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet
        from nordlet.purchases import PostV1PurchasesInvoicesCreateRequestLinesItem

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.purchases.post_v1purchases_invoices_create(
                partner_id="partnerId",
                document_number="documentNumber",
                document_date="documentDate",
                lines=[PostV1PurchasesInvoicesCreateRequestLinesItem()],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1purchases_invoices_create(
            partner_id=partner_id,
            document_number=document_number,
            document_date=document_date,
            lines=lines,
            type=type,
            due_date=due_date,
            currency=currency,
            credited_invoice_id=credited_invoice_id,
            notes=notes,
            request_options=request_options,
        )
        return _response.data

    async def post_v1purchases_invoices_get(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1PurchasesInvoicesGetResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PurchasesInvoicesGetResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.purchases.post_v1purchases_invoices_get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1purchases_invoices_get(id=id, request_options=request_options)
        return _response.data

    async def post_v1purchases_invoices_update(
        self,
        *,
        id: str,
        partner_id: typing.Optional[str] = OMIT,
        document_number: typing.Optional[str] = OMIT,
        document_date: typing.Optional[str] = OMIT,
        due_date: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        notes: typing.Optional[str] = OMIT,
        lines: typing.Optional[typing.Sequence[PostV1PurchasesInvoicesUpdateRequestLinesItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PurchasesInvoicesUpdateResponse:
        """
        Parameters
        ----------
        id : str

        partner_id : typing.Optional[str]

        document_number : typing.Optional[str]

        document_date : typing.Optional[str]

        due_date : typing.Optional[str]

        currency : typing.Optional[str]

        notes : typing.Optional[str]

        lines : typing.Optional[typing.Sequence[PostV1PurchasesInvoicesUpdateRequestLinesItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PurchasesInvoicesUpdateResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.purchases.post_v1purchases_invoices_update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1purchases_invoices_update(
            id=id,
            partner_id=partner_id,
            document_number=document_number,
            document_date=document_date,
            due_date=due_date,
            currency=currency,
            notes=notes,
            lines=lines,
            request_options=request_options,
        )
        return _response.data

    async def post_v1purchases_invoices_delete(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1PurchasesInvoicesDeleteResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PurchasesInvoicesDeleteResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.purchases.post_v1purchases_invoices_delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1purchases_invoices_delete(id=id, request_options=request_options)
        return _response.data

    async def post_v1purchases_invoices_register(
        self,
        *,
        id: str,
        registration_date: typing.Optional[str] = OMIT,
        warehouse_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PurchasesInvoicesRegisterResponse:
        """
        Parameters
        ----------
        id : str

        registration_date : typing.Optional[str]

        warehouse_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PurchasesInvoicesRegisterResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.purchases.post_v1purchases_invoices_register(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1purchases_invoices_register(
            id=id, registration_date=registration_date, warehouse_id=warehouse_id, request_options=request_options
        )
        return _response.data

    async def post_v1purchases_invoices_list(
        self,
        *,
        page: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        sort: typing.Optional[typing.Sequence[PostV1PurchasesInvoicesListRequestSortItem]] = OMIT,
        filter: typing.Optional[typing.Sequence[PostV1PurchasesInvoicesListRequestFilterItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1PurchasesInvoicesListResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[PostV1PurchasesInvoicesListRequestSortItem]]

        filter : typing.Optional[typing.Sequence[PostV1PurchasesInvoicesListRequestFilterItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1PurchasesInvoicesListResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.purchases.post_v1purchases_invoices_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1purchases_invoices_list(
            page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data
