# This file was auto-generated by Fern from our API Definition.

import typing

ErrorResponseErrorCode = typing.Union[
    typing.Literal[
        "validation",
        "unauthorized",
        "forbidden",
        "not_found",
        "conflict",
        "idempotency_key_reuse",
        "idempotency_in_progress",
        "rate_limited",
        "internal",
    ],
    typing.Any,
]
