# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class BooksImportMigrationResponseFixedAssets(UniversalBaseModel):
    created: int
    cost_total: typing_extensions.Annotated[str, FieldMetadata(alias="costTotal"), pydantic.Field(alias="costTotal")]
    accumulated_depreciation_total: typing_extensions.Annotated[
        str, FieldMetadata(alias="accumulatedDepreciationTotal"), pydantic.Field(alias="accumulatedDepreciationTotal")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
