# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .books_validate_migration_request_journal_item_entries_item import (
    BooksValidateMigrationRequestJournalItemEntriesItem,
)


class BooksValidateMigrationRequestJournalItem(UniversalBaseModel):
    date: dt.date
    description: typing.Optional[str] = None
    reference: typing.Optional[str] = None
    entries: typing.List[BooksValidateMigrationRequestJournalItemEntriesItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
