# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class PostV1MigrationBooksValidateRequestOpenPayablesItem(UniversalBaseModel):
    partner_code: typing_extensions.Annotated[
        str, FieldMetadata(alias="partnerCode"), pydantic.Field(alias="partnerCode")
    ]
    due_date: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="dueDate"), pydantic.Field(alias="dueDate")
    ] = None
    currency: typing.Optional[str] = None
    gross_total: typing_extensions.Annotated[str, FieldMetadata(alias="grossTotal"), pydantic.Field(alias="grossTotal")]
    vat_total: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="vatTotal"), pydantic.Field(alias="vatTotal")
    ] = None
    outstanding: typing.Optional[str] = None
    fx_rate: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="fxRate"), pydantic.Field(alias="fxRate")
    ] = None
    notes: typing.Optional[str] = None
    document_number: typing_extensions.Annotated[
        str, FieldMetadata(alias="documentNumber"), pydantic.Field(alias="documentNumber")
    ]
    document_date: typing_extensions.Annotated[
        str, FieldMetadata(alias="documentDate"), pydantic.Field(alias="documentDate")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
