# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .post_v1catalog_item_groups_create_response import PostV1CatalogItemGroupsCreateResponse
    from .post_v1catalog_item_groups_delete_response import PostV1CatalogItemGroupsDeleteResponse
    from .post_v1catalog_item_groups_list_response import PostV1CatalogItemGroupsListResponse
    from .post_v1catalog_item_groups_list_response_rows_item import PostV1CatalogItemGroupsListResponseRowsItem
    from .post_v1catalog_item_groups_update_response import PostV1CatalogItemGroupsUpdateResponse
    from .post_v1catalog_items_create_request_components_item import PostV1CatalogItemsCreateRequestComponentsItem
    from .post_v1catalog_items_create_request_translations_value import PostV1CatalogItemsCreateRequestTranslationsValue
    from .post_v1catalog_items_create_request_type import PostV1CatalogItemsCreateRequestType
    from .post_v1catalog_items_create_response import PostV1CatalogItemsCreateResponse
    from .post_v1catalog_items_create_response_components_item import PostV1CatalogItemsCreateResponseComponentsItem
    from .post_v1catalog_items_create_response_translations_value import (
        PostV1CatalogItemsCreateResponseTranslationsValue,
    )
    from .post_v1catalog_items_create_response_type import PostV1CatalogItemsCreateResponseType
    from .post_v1catalog_items_delete_response import PostV1CatalogItemsDeleteResponse
    from .post_v1catalog_items_get_response import PostV1CatalogItemsGetResponse
    from .post_v1catalog_items_get_response_components_item import PostV1CatalogItemsGetResponseComponentsItem
    from .post_v1catalog_items_get_response_translations_value import PostV1CatalogItemsGetResponseTranslationsValue
    from .post_v1catalog_items_get_response_type import PostV1CatalogItemsGetResponseType
    from .post_v1catalog_items_list_request_filter_item import PostV1CatalogItemsListRequestFilterItem
    from .post_v1catalog_items_list_request_filter_item_op import PostV1CatalogItemsListRequestFilterItemOp
    from .post_v1catalog_items_list_request_filter_item_value import PostV1CatalogItemsListRequestFilterItemValue
    from .post_v1catalog_items_list_request_filter_item_value_three_item import (
        PostV1CatalogItemsListRequestFilterItemValueThreeItem,
    )
    from .post_v1catalog_items_list_request_sort_item import PostV1CatalogItemsListRequestSortItem
    from .post_v1catalog_items_list_request_sort_item_dir import PostV1CatalogItemsListRequestSortItemDir
    from .post_v1catalog_items_list_response import PostV1CatalogItemsListResponse
    from .post_v1catalog_items_list_response_rows_item import PostV1CatalogItemsListResponseRowsItem
    from .post_v1catalog_items_list_response_rows_item_components_item import (
        PostV1CatalogItemsListResponseRowsItemComponentsItem,
    )
    from .post_v1catalog_items_list_response_rows_item_translations_value import (
        PostV1CatalogItemsListResponseRowsItemTranslationsValue,
    )
    from .post_v1catalog_items_list_response_rows_item_type import PostV1CatalogItemsListResponseRowsItemType
    from .post_v1catalog_items_suppliers_delete_response import PostV1CatalogItemsSuppliersDeleteResponse
    from .post_v1catalog_items_suppliers_list_response import PostV1CatalogItemsSuppliersListResponse
    from .post_v1catalog_items_suppliers_list_response_rows_item import PostV1CatalogItemsSuppliersListResponseRowsItem
    from .post_v1catalog_items_suppliers_upsert_response import PostV1CatalogItemsSuppliersUpsertResponse
    from .post_v1catalog_items_update_request_components_item import PostV1CatalogItemsUpdateRequestComponentsItem
    from .post_v1catalog_items_update_request_translations_value import PostV1CatalogItemsUpdateRequestTranslationsValue
    from .post_v1catalog_items_update_request_type import PostV1CatalogItemsUpdateRequestType
    from .post_v1catalog_items_update_response import PostV1CatalogItemsUpdateResponse
    from .post_v1catalog_items_update_response_components_item import PostV1CatalogItemsUpdateResponseComponentsItem
    from .post_v1catalog_items_update_response_translations_value import (
        PostV1CatalogItemsUpdateResponseTranslationsValue,
    )
    from .post_v1catalog_items_update_response_type import PostV1CatalogItemsUpdateResponseType
    from .post_v1catalog_price_lists_create_response import PostV1CatalogPriceListsCreateResponse
    from .post_v1catalog_price_lists_items_delete_response import PostV1CatalogPriceListsItemsDeleteResponse
    from .post_v1catalog_price_lists_items_list_response import PostV1CatalogPriceListsItemsListResponse
    from .post_v1catalog_price_lists_items_list_response_rows_item import (
        PostV1CatalogPriceListsItemsListResponseRowsItem,
    )
    from .post_v1catalog_price_lists_items_set_request_items_item import PostV1CatalogPriceListsItemsSetRequestItemsItem
    from .post_v1catalog_price_lists_items_set_response import PostV1CatalogPriceListsItemsSetResponse
    from .post_v1catalog_price_lists_list_response import PostV1CatalogPriceListsListResponse
    from .post_v1catalog_price_lists_list_response_rows_item import PostV1CatalogPriceListsListResponseRowsItem
    from .post_v1catalog_price_lists_update_response import PostV1CatalogPriceListsUpdateResponse
_dynamic_imports: typing.Dict[str, str] = {
    "PostV1CatalogItemGroupsCreateResponse": ".post_v1catalog_item_groups_create_response",
    "PostV1CatalogItemGroupsDeleteResponse": ".post_v1catalog_item_groups_delete_response",
    "PostV1CatalogItemGroupsListResponse": ".post_v1catalog_item_groups_list_response",
    "PostV1CatalogItemGroupsListResponseRowsItem": ".post_v1catalog_item_groups_list_response_rows_item",
    "PostV1CatalogItemGroupsUpdateResponse": ".post_v1catalog_item_groups_update_response",
    "PostV1CatalogItemsCreateRequestComponentsItem": ".post_v1catalog_items_create_request_components_item",
    "PostV1CatalogItemsCreateRequestTranslationsValue": ".post_v1catalog_items_create_request_translations_value",
    "PostV1CatalogItemsCreateRequestType": ".post_v1catalog_items_create_request_type",
    "PostV1CatalogItemsCreateResponse": ".post_v1catalog_items_create_response",
    "PostV1CatalogItemsCreateResponseComponentsItem": ".post_v1catalog_items_create_response_components_item",
    "PostV1CatalogItemsCreateResponseTranslationsValue": ".post_v1catalog_items_create_response_translations_value",
    "PostV1CatalogItemsCreateResponseType": ".post_v1catalog_items_create_response_type",
    "PostV1CatalogItemsDeleteResponse": ".post_v1catalog_items_delete_response",
    "PostV1CatalogItemsGetResponse": ".post_v1catalog_items_get_response",
    "PostV1CatalogItemsGetResponseComponentsItem": ".post_v1catalog_items_get_response_components_item",
    "PostV1CatalogItemsGetResponseTranslationsValue": ".post_v1catalog_items_get_response_translations_value",
    "PostV1CatalogItemsGetResponseType": ".post_v1catalog_items_get_response_type",
    "PostV1CatalogItemsListRequestFilterItem": ".post_v1catalog_items_list_request_filter_item",
    "PostV1CatalogItemsListRequestFilterItemOp": ".post_v1catalog_items_list_request_filter_item_op",
    "PostV1CatalogItemsListRequestFilterItemValue": ".post_v1catalog_items_list_request_filter_item_value",
    "PostV1CatalogItemsListRequestFilterItemValueThreeItem": ".post_v1catalog_items_list_request_filter_item_value_three_item",
    "PostV1CatalogItemsListRequestSortItem": ".post_v1catalog_items_list_request_sort_item",
    "PostV1CatalogItemsListRequestSortItemDir": ".post_v1catalog_items_list_request_sort_item_dir",
    "PostV1CatalogItemsListResponse": ".post_v1catalog_items_list_response",
    "PostV1CatalogItemsListResponseRowsItem": ".post_v1catalog_items_list_response_rows_item",
    "PostV1CatalogItemsListResponseRowsItemComponentsItem": ".post_v1catalog_items_list_response_rows_item_components_item",
    "PostV1CatalogItemsListResponseRowsItemTranslationsValue": ".post_v1catalog_items_list_response_rows_item_translations_value",
    "PostV1CatalogItemsListResponseRowsItemType": ".post_v1catalog_items_list_response_rows_item_type",
    "PostV1CatalogItemsSuppliersDeleteResponse": ".post_v1catalog_items_suppliers_delete_response",
    "PostV1CatalogItemsSuppliersListResponse": ".post_v1catalog_items_suppliers_list_response",
    "PostV1CatalogItemsSuppliersListResponseRowsItem": ".post_v1catalog_items_suppliers_list_response_rows_item",
    "PostV1CatalogItemsSuppliersUpsertResponse": ".post_v1catalog_items_suppliers_upsert_response",
    "PostV1CatalogItemsUpdateRequestComponentsItem": ".post_v1catalog_items_update_request_components_item",
    "PostV1CatalogItemsUpdateRequestTranslationsValue": ".post_v1catalog_items_update_request_translations_value",
    "PostV1CatalogItemsUpdateRequestType": ".post_v1catalog_items_update_request_type",
    "PostV1CatalogItemsUpdateResponse": ".post_v1catalog_items_update_response",
    "PostV1CatalogItemsUpdateResponseComponentsItem": ".post_v1catalog_items_update_response_components_item",
    "PostV1CatalogItemsUpdateResponseTranslationsValue": ".post_v1catalog_items_update_response_translations_value",
    "PostV1CatalogItemsUpdateResponseType": ".post_v1catalog_items_update_response_type",
    "PostV1CatalogPriceListsCreateResponse": ".post_v1catalog_price_lists_create_response",
    "PostV1CatalogPriceListsItemsDeleteResponse": ".post_v1catalog_price_lists_items_delete_response",
    "PostV1CatalogPriceListsItemsListResponse": ".post_v1catalog_price_lists_items_list_response",
    "PostV1CatalogPriceListsItemsListResponseRowsItem": ".post_v1catalog_price_lists_items_list_response_rows_item",
    "PostV1CatalogPriceListsItemsSetRequestItemsItem": ".post_v1catalog_price_lists_items_set_request_items_item",
    "PostV1CatalogPriceListsItemsSetResponse": ".post_v1catalog_price_lists_items_set_response",
    "PostV1CatalogPriceListsListResponse": ".post_v1catalog_price_lists_list_response",
    "PostV1CatalogPriceListsListResponseRowsItem": ".post_v1catalog_price_lists_list_response_rows_item",
    "PostV1CatalogPriceListsUpdateResponse": ".post_v1catalog_price_lists_update_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "PostV1CatalogItemGroupsCreateResponse",
    "PostV1CatalogItemGroupsDeleteResponse",
    "PostV1CatalogItemGroupsListResponse",
    "PostV1CatalogItemGroupsListResponseRowsItem",
    "PostV1CatalogItemGroupsUpdateResponse",
    "PostV1CatalogItemsCreateRequestComponentsItem",
    "PostV1CatalogItemsCreateRequestTranslationsValue",
    "PostV1CatalogItemsCreateRequestType",
    "PostV1CatalogItemsCreateResponse",
    "PostV1CatalogItemsCreateResponseComponentsItem",
    "PostV1CatalogItemsCreateResponseTranslationsValue",
    "PostV1CatalogItemsCreateResponseType",
    "PostV1CatalogItemsDeleteResponse",
    "PostV1CatalogItemsGetResponse",
    "PostV1CatalogItemsGetResponseComponentsItem",
    "PostV1CatalogItemsGetResponseTranslationsValue",
    "PostV1CatalogItemsGetResponseType",
    "PostV1CatalogItemsListRequestFilterItem",
    "PostV1CatalogItemsListRequestFilterItemOp",
    "PostV1CatalogItemsListRequestFilterItemValue",
    "PostV1CatalogItemsListRequestFilterItemValueThreeItem",
    "PostV1CatalogItemsListRequestSortItem",
    "PostV1CatalogItemsListRequestSortItemDir",
    "PostV1CatalogItemsListResponse",
    "PostV1CatalogItemsListResponseRowsItem",
    "PostV1CatalogItemsListResponseRowsItemComponentsItem",
    "PostV1CatalogItemsListResponseRowsItemTranslationsValue",
    "PostV1CatalogItemsListResponseRowsItemType",
    "PostV1CatalogItemsSuppliersDeleteResponse",
    "PostV1CatalogItemsSuppliersListResponse",
    "PostV1CatalogItemsSuppliersListResponseRowsItem",
    "PostV1CatalogItemsSuppliersUpsertResponse",
    "PostV1CatalogItemsUpdateRequestComponentsItem",
    "PostV1CatalogItemsUpdateRequestTranslationsValue",
    "PostV1CatalogItemsUpdateRequestType",
    "PostV1CatalogItemsUpdateResponse",
    "PostV1CatalogItemsUpdateResponseComponentsItem",
    "PostV1CatalogItemsUpdateResponseTranslationsValue",
    "PostV1CatalogItemsUpdateResponseType",
    "PostV1CatalogPriceListsCreateResponse",
    "PostV1CatalogPriceListsItemsDeleteResponse",
    "PostV1CatalogPriceListsItemsListResponse",
    "PostV1CatalogPriceListsItemsListResponseRowsItem",
    "PostV1CatalogPriceListsItemsSetRequestItemsItem",
    "PostV1CatalogPriceListsItemsSetResponse",
    "PostV1CatalogPriceListsListResponse",
    "PostV1CatalogPriceListsListResponseRowsItem",
    "PostV1CatalogPriceListsUpdateResponse",
]
