# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_v1declarations_lt_intrastat_compute_response_counts import PostV1DeclarationsLtIntrastatComputeResponseCounts
from .post_v1declarations_lt_intrastat_compute_response_flow import PostV1DeclarationsLtIntrastatComputeResponseFlow
from .post_v1declarations_lt_intrastat_compute_response_rows_item import (
    PostV1DeclarationsLtIntrastatComputeResponseRowsItem,
)
from .post_v1declarations_lt_intrastat_compute_response_totals import PostV1DeclarationsLtIntrastatComputeResponseTotals


class PostV1DeclarationsLtIntrastatComputeResponse(UniversalBaseModel):
    flow: PostV1DeclarationsLtIntrastatComputeResponseFlow
    reference_period: typing_extensions.Annotated[
        str, FieldMetadata(alias="referencePeriod"), pydantic.Field(alias="referencePeriod")
    ]
    period_start: typing_extensions.Annotated[
        str, FieldMetadata(alias="periodStart"), pydantic.Field(alias="periodStart")
    ]
    period_end: typing_extensions.Annotated[str, FieldMetadata(alias="periodEnd"), pydantic.Field(alias="periodEnd")]
    file_name: typing_extensions.Annotated[str, FieldMetadata(alias="fileName"), pydantic.Field(alias="fileName")]
    file_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="fileId"), pydantic.Field(alias="fileId")
    ] = None
    rows: typing.List[PostV1DeclarationsLtIntrastatComputeResponseRowsItem]
    totals: PostV1DeclarationsLtIntrastatComputeResponseTotals
    counts: PostV1DeclarationsLtIntrastatComputeResponseCounts
    warnings: typing.List[str]
    notes: typing.List[str]
    xml: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
