# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .certificates_upload_declarations_response_rows_item_format import (
    CertificatesUploadDeclarationsResponseRowsItemFormat,
)
from .certificates_upload_declarations_response_rows_item_health import (
    CertificatesUploadDeclarationsResponseRowsItemHealth,
)


class CertificatesUploadDeclarationsResponseRowsItem(UniversalBaseModel):
    id: str
    system: str
    field_key: typing_extensions.Annotated[str, FieldMetadata(alias="fieldKey"), pydantic.Field(alias="fieldKey")]
    file_name: typing_extensions.Annotated[str, FieldMetadata(alias="fileName"), pydantic.Field(alias="fileName")]
    format: CertificatesUploadDeclarationsResponseRowsItemFormat
    fingerprint: typing.Optional[str] = None
    subject: typing.Optional[str] = None
    issuer: typing.Optional[str] = None
    not_before: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="notBefore"), pydantic.Field(alias="notBefore")
    ] = None
    not_after: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="notAfter"), pydantic.Field(alias="notAfter")
    ] = None
    sha256: str
    health: CertificatesUploadDeclarationsResponseRowsItemHealth
    days_left: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="daysLeft"), pydantic.Field(alias="daysLeft")
    ] = None
    uploaded_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="uploadedAt"), pydantic.Field(alias="uploadedAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
