# This file was auto-generated by Fern from our API Definition.

import typing

EuDigitalReportingListDeclarationsResponseTransactionsItemDocumentType = typing.Union[
    typing.Literal["invoice", "credit_note"], typing.Any
]
