# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_v1declarations_ee_employment_register_send_response_state import (
    PostV1DeclarationsEeEmploymentRegisterSendResponseState,
)


class PostV1DeclarationsEeEmploymentRegisterSendResponse(UniversalBaseModel):
    reference: str
    state: PostV1DeclarationsEeEmploymentRegisterSendResponseState
    detail: typing.Optional[str] = None
    file_name: typing_extensions.Annotated[str, FieldMetadata(alias="fileName"), pydantic.Field(alias="fileName")]
    entry_date: typing_extensions.Annotated[str, FieldMetadata(alias="entryDate"), pydantic.Field(alias="entryDate")]
    xml: str
    warnings: typing.List[str]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
