# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_v1declarations_eu_ioss_compute_response_rows_item_rate_type import (
    PostV1DeclarationsEuIossComputeResponseRowsItemRateType,
)


class PostV1DeclarationsEuIossComputeResponseRowsItem(UniversalBaseModel):
    country_code: typing_extensions.Annotated[
        str, FieldMetadata(alias="countryCode"), pydantic.Field(alias="countryCode")
    ]
    rate_type: typing_extensions.Annotated[
        PostV1DeclarationsEuIossComputeResponseRowsItemRateType,
        FieldMetadata(alias="rateType"),
        pydantic.Field(alias="rateType"),
    ]
    vat_rate_percent: typing_extensions.Annotated[
        str, FieldMetadata(alias="vatRatePercent"), pydantic.Field(alias="vatRatePercent")
    ]
    taxable_amount: typing_extensions.Annotated[
        str, FieldMetadata(alias="taxableAmount"), pydantic.Field(alias="taxableAmount")
    ]
    vat_amount: typing_extensions.Annotated[str, FieldMetadata(alias="vatAmount"), pydantic.Field(alias="vatAmount")]
    documents: int

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
