# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .post_v1agreements_agreements_billing_run_response import PostV1AgreementsAgreementsBillingRunResponse
    from .post_v1agreements_agreements_billing_run_response_errors_item import (
        PostV1AgreementsAgreementsBillingRunResponseErrorsItem,
    )
    from .post_v1agreements_agreements_billing_run_response_generated_item import (
        PostV1AgreementsAgreementsBillingRunResponseGeneratedItem,
    )
    from .post_v1agreements_agreements_create_request_billing_period import (
        PostV1AgreementsAgreementsCreateRequestBillingPeriod,
    )
    from .post_v1agreements_agreements_create_request_items_item import PostV1AgreementsAgreementsCreateRequestItemsItem
    from .post_v1agreements_agreements_create_request_kind import PostV1AgreementsAgreementsCreateRequestKind
    from .post_v1agreements_agreements_create_request_status import PostV1AgreementsAgreementsCreateRequestStatus
    from .post_v1agreements_agreements_create_response import PostV1AgreementsAgreementsCreateResponse
    from .post_v1agreements_agreements_create_response_billing_period import (
        PostV1AgreementsAgreementsCreateResponseBillingPeriod,
    )
    from .post_v1agreements_agreements_create_response_items_item import (
        PostV1AgreementsAgreementsCreateResponseItemsItem,
    )
    from .post_v1agreements_agreements_create_response_kind import PostV1AgreementsAgreementsCreateResponseKind
    from .post_v1agreements_agreements_create_response_status import PostV1AgreementsAgreementsCreateResponseStatus
    from .post_v1agreements_agreements_delete_response import PostV1AgreementsAgreementsDeleteResponse
    from .post_v1agreements_agreements_generate_invoice_response import (
        PostV1AgreementsAgreementsGenerateInvoiceResponse,
    )
    from .post_v1agreements_agreements_get_response import PostV1AgreementsAgreementsGetResponse
    from .post_v1agreements_agreements_get_response_billing_period import (
        PostV1AgreementsAgreementsGetResponseBillingPeriod,
    )
    from .post_v1agreements_agreements_get_response_items_item import PostV1AgreementsAgreementsGetResponseItemsItem
    from .post_v1agreements_agreements_get_response_kind import PostV1AgreementsAgreementsGetResponseKind
    from .post_v1agreements_agreements_get_response_status import PostV1AgreementsAgreementsGetResponseStatus
    from .post_v1agreements_agreements_list_request_filter_item import PostV1AgreementsAgreementsListRequestFilterItem
    from .post_v1agreements_agreements_list_request_filter_item_op import (
        PostV1AgreementsAgreementsListRequestFilterItemOp,
    )
    from .post_v1agreements_agreements_list_request_filter_item_value import (
        PostV1AgreementsAgreementsListRequestFilterItemValue,
    )
    from .post_v1agreements_agreements_list_request_filter_item_value_three_item import (
        PostV1AgreementsAgreementsListRequestFilterItemValueThreeItem,
    )
    from .post_v1agreements_agreements_list_request_sort_item import PostV1AgreementsAgreementsListRequestSortItem
    from .post_v1agreements_agreements_list_request_sort_item_dir import (
        PostV1AgreementsAgreementsListRequestSortItemDir,
    )
    from .post_v1agreements_agreements_list_response import PostV1AgreementsAgreementsListResponse
    from .post_v1agreements_agreements_list_response_rows_item import PostV1AgreementsAgreementsListResponseRowsItem
    from .post_v1agreements_agreements_list_response_rows_item_billing_period import (
        PostV1AgreementsAgreementsListResponseRowsItemBillingPeriod,
    )
    from .post_v1agreements_agreements_list_response_rows_item_kind import (
        PostV1AgreementsAgreementsListResponseRowsItemKind,
    )
    from .post_v1agreements_agreements_list_response_rows_item_status import (
        PostV1AgreementsAgreementsListResponseRowsItemStatus,
    )
    from .post_v1agreements_agreements_update_request_billing_period import (
        PostV1AgreementsAgreementsUpdateRequestBillingPeriod,
    )
    from .post_v1agreements_agreements_update_request_kind import PostV1AgreementsAgreementsUpdateRequestKind
    from .post_v1agreements_agreements_update_request_status import PostV1AgreementsAgreementsUpdateRequestStatus
    from .post_v1agreements_agreements_update_response import PostV1AgreementsAgreementsUpdateResponse
    from .post_v1agreements_agreements_update_response_billing_period import (
        PostV1AgreementsAgreementsUpdateResponseBillingPeriod,
    )
    from .post_v1agreements_agreements_update_response_items_item import (
        PostV1AgreementsAgreementsUpdateResponseItemsItem,
    )
    from .post_v1agreements_agreements_update_response_kind import PostV1AgreementsAgreementsUpdateResponseKind
    from .post_v1agreements_agreements_update_response_status import PostV1AgreementsAgreementsUpdateResponseStatus
    from .post_v1agreements_insurance_policies_create_response import PostV1AgreementsInsurancePoliciesCreateResponse
    from .post_v1agreements_insurance_policies_delete_response import PostV1AgreementsInsurancePoliciesDeleteResponse
    from .post_v1agreements_insurance_policies_list_request_filter_item import (
        PostV1AgreementsInsurancePoliciesListRequestFilterItem,
    )
    from .post_v1agreements_insurance_policies_list_request_filter_item_op import (
        PostV1AgreementsInsurancePoliciesListRequestFilterItemOp,
    )
    from .post_v1agreements_insurance_policies_list_request_filter_item_value import (
        PostV1AgreementsInsurancePoliciesListRequestFilterItemValue,
    )
    from .post_v1agreements_insurance_policies_list_request_filter_item_value_three_item import (
        PostV1AgreementsInsurancePoliciesListRequestFilterItemValueThreeItem,
    )
    from .post_v1agreements_insurance_policies_list_request_sort_item import (
        PostV1AgreementsInsurancePoliciesListRequestSortItem,
    )
    from .post_v1agreements_insurance_policies_list_request_sort_item_dir import (
        PostV1AgreementsInsurancePoliciesListRequestSortItemDir,
    )
    from .post_v1agreements_insurance_policies_list_response import PostV1AgreementsInsurancePoliciesListResponse
    from .post_v1agreements_insurance_policies_list_response_rows_item import (
        PostV1AgreementsInsurancePoliciesListResponseRowsItem,
    )
    from .post_v1agreements_types_create_response import PostV1AgreementsTypesCreateResponse
    from .post_v1agreements_types_list_request_filter_item import PostV1AgreementsTypesListRequestFilterItem
    from .post_v1agreements_types_list_request_filter_item_op import PostV1AgreementsTypesListRequestFilterItemOp
    from .post_v1agreements_types_list_request_filter_item_value import PostV1AgreementsTypesListRequestFilterItemValue
    from .post_v1agreements_types_list_request_filter_item_value_three_item import (
        PostV1AgreementsTypesListRequestFilterItemValueThreeItem,
    )
    from .post_v1agreements_types_list_request_sort_item import PostV1AgreementsTypesListRequestSortItem
    from .post_v1agreements_types_list_request_sort_item_dir import PostV1AgreementsTypesListRequestSortItemDir
    from .post_v1agreements_types_list_response import PostV1AgreementsTypesListResponse
    from .post_v1agreements_types_list_response_rows_item import PostV1AgreementsTypesListResponseRowsItem
_dynamic_imports: typing.Dict[str, str] = {
    "PostV1AgreementsAgreementsBillingRunResponse": ".post_v1agreements_agreements_billing_run_response",
    "PostV1AgreementsAgreementsBillingRunResponseErrorsItem": ".post_v1agreements_agreements_billing_run_response_errors_item",
    "PostV1AgreementsAgreementsBillingRunResponseGeneratedItem": ".post_v1agreements_agreements_billing_run_response_generated_item",
    "PostV1AgreementsAgreementsCreateRequestBillingPeriod": ".post_v1agreements_agreements_create_request_billing_period",
    "PostV1AgreementsAgreementsCreateRequestItemsItem": ".post_v1agreements_agreements_create_request_items_item",
    "PostV1AgreementsAgreementsCreateRequestKind": ".post_v1agreements_agreements_create_request_kind",
    "PostV1AgreementsAgreementsCreateRequestStatus": ".post_v1agreements_agreements_create_request_status",
    "PostV1AgreementsAgreementsCreateResponse": ".post_v1agreements_agreements_create_response",
    "PostV1AgreementsAgreementsCreateResponseBillingPeriod": ".post_v1agreements_agreements_create_response_billing_period",
    "PostV1AgreementsAgreementsCreateResponseItemsItem": ".post_v1agreements_agreements_create_response_items_item",
    "PostV1AgreementsAgreementsCreateResponseKind": ".post_v1agreements_agreements_create_response_kind",
    "PostV1AgreementsAgreementsCreateResponseStatus": ".post_v1agreements_agreements_create_response_status",
    "PostV1AgreementsAgreementsDeleteResponse": ".post_v1agreements_agreements_delete_response",
    "PostV1AgreementsAgreementsGenerateInvoiceResponse": ".post_v1agreements_agreements_generate_invoice_response",
    "PostV1AgreementsAgreementsGetResponse": ".post_v1agreements_agreements_get_response",
    "PostV1AgreementsAgreementsGetResponseBillingPeriod": ".post_v1agreements_agreements_get_response_billing_period",
    "PostV1AgreementsAgreementsGetResponseItemsItem": ".post_v1agreements_agreements_get_response_items_item",
    "PostV1AgreementsAgreementsGetResponseKind": ".post_v1agreements_agreements_get_response_kind",
    "PostV1AgreementsAgreementsGetResponseStatus": ".post_v1agreements_agreements_get_response_status",
    "PostV1AgreementsAgreementsListRequestFilterItem": ".post_v1agreements_agreements_list_request_filter_item",
    "PostV1AgreementsAgreementsListRequestFilterItemOp": ".post_v1agreements_agreements_list_request_filter_item_op",
    "PostV1AgreementsAgreementsListRequestFilterItemValue": ".post_v1agreements_agreements_list_request_filter_item_value",
    "PostV1AgreementsAgreementsListRequestFilterItemValueThreeItem": ".post_v1agreements_agreements_list_request_filter_item_value_three_item",
    "PostV1AgreementsAgreementsListRequestSortItem": ".post_v1agreements_agreements_list_request_sort_item",
    "PostV1AgreementsAgreementsListRequestSortItemDir": ".post_v1agreements_agreements_list_request_sort_item_dir",
    "PostV1AgreementsAgreementsListResponse": ".post_v1agreements_agreements_list_response",
    "PostV1AgreementsAgreementsListResponseRowsItem": ".post_v1agreements_agreements_list_response_rows_item",
    "PostV1AgreementsAgreementsListResponseRowsItemBillingPeriod": ".post_v1agreements_agreements_list_response_rows_item_billing_period",
    "PostV1AgreementsAgreementsListResponseRowsItemKind": ".post_v1agreements_agreements_list_response_rows_item_kind",
    "PostV1AgreementsAgreementsListResponseRowsItemStatus": ".post_v1agreements_agreements_list_response_rows_item_status",
    "PostV1AgreementsAgreementsUpdateRequestBillingPeriod": ".post_v1agreements_agreements_update_request_billing_period",
    "PostV1AgreementsAgreementsUpdateRequestKind": ".post_v1agreements_agreements_update_request_kind",
    "PostV1AgreementsAgreementsUpdateRequestStatus": ".post_v1agreements_agreements_update_request_status",
    "PostV1AgreementsAgreementsUpdateResponse": ".post_v1agreements_agreements_update_response",
    "PostV1AgreementsAgreementsUpdateResponseBillingPeriod": ".post_v1agreements_agreements_update_response_billing_period",
    "PostV1AgreementsAgreementsUpdateResponseItemsItem": ".post_v1agreements_agreements_update_response_items_item",
    "PostV1AgreementsAgreementsUpdateResponseKind": ".post_v1agreements_agreements_update_response_kind",
    "PostV1AgreementsAgreementsUpdateResponseStatus": ".post_v1agreements_agreements_update_response_status",
    "PostV1AgreementsInsurancePoliciesCreateResponse": ".post_v1agreements_insurance_policies_create_response",
    "PostV1AgreementsInsurancePoliciesDeleteResponse": ".post_v1agreements_insurance_policies_delete_response",
    "PostV1AgreementsInsurancePoliciesListRequestFilterItem": ".post_v1agreements_insurance_policies_list_request_filter_item",
    "PostV1AgreementsInsurancePoliciesListRequestFilterItemOp": ".post_v1agreements_insurance_policies_list_request_filter_item_op",
    "PostV1AgreementsInsurancePoliciesListRequestFilterItemValue": ".post_v1agreements_insurance_policies_list_request_filter_item_value",
    "PostV1AgreementsInsurancePoliciesListRequestFilterItemValueThreeItem": ".post_v1agreements_insurance_policies_list_request_filter_item_value_three_item",
    "PostV1AgreementsInsurancePoliciesListRequestSortItem": ".post_v1agreements_insurance_policies_list_request_sort_item",
    "PostV1AgreementsInsurancePoliciesListRequestSortItemDir": ".post_v1agreements_insurance_policies_list_request_sort_item_dir",
    "PostV1AgreementsInsurancePoliciesListResponse": ".post_v1agreements_insurance_policies_list_response",
    "PostV1AgreementsInsurancePoliciesListResponseRowsItem": ".post_v1agreements_insurance_policies_list_response_rows_item",
    "PostV1AgreementsTypesCreateResponse": ".post_v1agreements_types_create_response",
    "PostV1AgreementsTypesListRequestFilterItem": ".post_v1agreements_types_list_request_filter_item",
    "PostV1AgreementsTypesListRequestFilterItemOp": ".post_v1agreements_types_list_request_filter_item_op",
    "PostV1AgreementsTypesListRequestFilterItemValue": ".post_v1agreements_types_list_request_filter_item_value",
    "PostV1AgreementsTypesListRequestFilterItemValueThreeItem": ".post_v1agreements_types_list_request_filter_item_value_three_item",
    "PostV1AgreementsTypesListRequestSortItem": ".post_v1agreements_types_list_request_sort_item",
    "PostV1AgreementsTypesListRequestSortItemDir": ".post_v1agreements_types_list_request_sort_item_dir",
    "PostV1AgreementsTypesListResponse": ".post_v1agreements_types_list_response",
    "PostV1AgreementsTypesListResponseRowsItem": ".post_v1agreements_types_list_response_rows_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "PostV1AgreementsAgreementsBillingRunResponse",
    "PostV1AgreementsAgreementsBillingRunResponseErrorsItem",
    "PostV1AgreementsAgreementsBillingRunResponseGeneratedItem",
    "PostV1AgreementsAgreementsCreateRequestBillingPeriod",
    "PostV1AgreementsAgreementsCreateRequestItemsItem",
    "PostV1AgreementsAgreementsCreateRequestKind",
    "PostV1AgreementsAgreementsCreateRequestStatus",
    "PostV1AgreementsAgreementsCreateResponse",
    "PostV1AgreementsAgreementsCreateResponseBillingPeriod",
    "PostV1AgreementsAgreementsCreateResponseItemsItem",
    "PostV1AgreementsAgreementsCreateResponseKind",
    "PostV1AgreementsAgreementsCreateResponseStatus",
    "PostV1AgreementsAgreementsDeleteResponse",
    "PostV1AgreementsAgreementsGenerateInvoiceResponse",
    "PostV1AgreementsAgreementsGetResponse",
    "PostV1AgreementsAgreementsGetResponseBillingPeriod",
    "PostV1AgreementsAgreementsGetResponseItemsItem",
    "PostV1AgreementsAgreementsGetResponseKind",
    "PostV1AgreementsAgreementsGetResponseStatus",
    "PostV1AgreementsAgreementsListRequestFilterItem",
    "PostV1AgreementsAgreementsListRequestFilterItemOp",
    "PostV1AgreementsAgreementsListRequestFilterItemValue",
    "PostV1AgreementsAgreementsListRequestFilterItemValueThreeItem",
    "PostV1AgreementsAgreementsListRequestSortItem",
    "PostV1AgreementsAgreementsListRequestSortItemDir",
    "PostV1AgreementsAgreementsListResponse",
    "PostV1AgreementsAgreementsListResponseRowsItem",
    "PostV1AgreementsAgreementsListResponseRowsItemBillingPeriod",
    "PostV1AgreementsAgreementsListResponseRowsItemKind",
    "PostV1AgreementsAgreementsListResponseRowsItemStatus",
    "PostV1AgreementsAgreementsUpdateRequestBillingPeriod",
    "PostV1AgreementsAgreementsUpdateRequestKind",
    "PostV1AgreementsAgreementsUpdateRequestStatus",
    "PostV1AgreementsAgreementsUpdateResponse",
    "PostV1AgreementsAgreementsUpdateResponseBillingPeriod",
    "PostV1AgreementsAgreementsUpdateResponseItemsItem",
    "PostV1AgreementsAgreementsUpdateResponseKind",
    "PostV1AgreementsAgreementsUpdateResponseStatus",
    "PostV1AgreementsInsurancePoliciesCreateResponse",
    "PostV1AgreementsInsurancePoliciesDeleteResponse",
    "PostV1AgreementsInsurancePoliciesListRequestFilterItem",
    "PostV1AgreementsInsurancePoliciesListRequestFilterItemOp",
    "PostV1AgreementsInsurancePoliciesListRequestFilterItemValue",
    "PostV1AgreementsInsurancePoliciesListRequestFilterItemValueThreeItem",
    "PostV1AgreementsInsurancePoliciesListRequestSortItem",
    "PostV1AgreementsInsurancePoliciesListRequestSortItemDir",
    "PostV1AgreementsInsurancePoliciesListResponse",
    "PostV1AgreementsInsurancePoliciesListResponseRowsItem",
    "PostV1AgreementsTypesCreateResponse",
    "PostV1AgreementsTypesListRequestFilterItem",
    "PostV1AgreementsTypesListRequestFilterItemOp",
    "PostV1AgreementsTypesListRequestFilterItemValue",
    "PostV1AgreementsTypesListRequestFilterItemValueThreeItem",
    "PostV1AgreementsTypesListRequestSortItem",
    "PostV1AgreementsTypesListRequestSortItemDir",
    "PostV1AgreementsTypesListResponse",
    "PostV1AgreementsTypesListResponseRowsItem",
]
