# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agreements_list_agreements_request_filter_item_op import AgreementsListAgreementsRequestFilterItemOp
from .agreements_list_agreements_request_filter_item_value import AgreementsListAgreementsRequestFilterItemValue


class AgreementsListAgreementsRequestFilterItem(UniversalBaseModel):
    field: str
    op: AgreementsListAgreementsRequestFilterItemOp
    value: AgreementsListAgreementsRequestFilterItemValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
