# This file was auto-generated by Fern from our API Definition.

import typing

AgreementsGetAgreementsResponseStatus = typing.Union[
    typing.Literal["draft", "active", "expired", "terminated"], typing.Any
]
