# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_v1agreements_agreements_billing_run_response_errors_item import (
    PostV1AgreementsAgreementsBillingRunResponseErrorsItem,
)
from .post_v1agreements_agreements_billing_run_response_generated_item import (
    PostV1AgreementsAgreementsBillingRunResponseGeneratedItem,
)


class PostV1AgreementsAgreementsBillingRunResponse(UniversalBaseModel):
    generated: typing.List[PostV1AgreementsAgreementsBillingRunResponseGeneratedItem]
    expired: typing.List[str]
    errors: typing.List[PostV1AgreementsAgreementsBillingRunResponseErrorsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
