# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_v1agreements_agreements_list_response_rows_item_billing_period import (
    PostV1AgreementsAgreementsListResponseRowsItemBillingPeriod,
)
from .post_v1agreements_agreements_list_response_rows_item_status import (
    PostV1AgreementsAgreementsListResponseRowsItemStatus,
)


class PostV1AgreementsAgreementsListResponseRowsItem(UniversalBaseModel):
    id: str
    type_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="typeId"), pydantic.Field(alias="typeId")
    ] = None
    partner_id: typing_extensions.Annotated[str, FieldMetadata(alias="partnerId"), pydantic.Field(alias="partnerId")]
    number: str
    name: typing.Optional[str] = None
    start_date: typing_extensions.Annotated[str, FieldMetadata(alias="startDate"), pydantic.Field(alias="startDate")]
    end_date: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="endDate"), pydantic.Field(alias="endDate")
    ] = None
    auto_renew: typing_extensions.Annotated[bool, FieldMetadata(alias="autoRenew"), pydantic.Field(alias="autoRenew")]
    value: typing.Optional[str] = None
    billing_period: typing_extensions.Annotated[
        typing.Optional[PostV1AgreementsAgreementsListResponseRowsItemBillingPeriod],
        FieldMetadata(alias="billingPeriod"),
        pydantic.Field(alias="billingPeriod"),
    ] = None
    currency: str
    status: PostV1AgreementsAgreementsListResponseRowsItemStatus
    notes: typing.Optional[str] = None
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
