# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .landed_costs_create_inventory_request_method import LandedCostsCreateInventoryRequestMethod
    from .landed_costs_create_inventory_response import LandedCostsCreateInventoryResponse
    from .landed_costs_create_inventory_response_lines_item import LandedCostsCreateInventoryResponseLinesItem
    from .landed_costs_create_inventory_response_method import LandedCostsCreateInventoryResponseMethod
    from .landed_costs_get_inventory_response import LandedCostsGetInventoryResponse
    from .landed_costs_get_inventory_response_lines_item import LandedCostsGetInventoryResponseLinesItem
    from .landed_costs_get_inventory_response_method import LandedCostsGetInventoryResponseMethod
    from .landed_costs_list_inventory_request_filter_item import LandedCostsListInventoryRequestFilterItem
    from .landed_costs_list_inventory_request_filter_item_op import LandedCostsListInventoryRequestFilterItemOp
    from .landed_costs_list_inventory_request_filter_item_value import LandedCostsListInventoryRequestFilterItemValue
    from .landed_costs_list_inventory_request_filter_item_value_three_item import (
        LandedCostsListInventoryRequestFilterItemValueThreeItem,
    )
    from .landed_costs_list_inventory_request_sort_item import LandedCostsListInventoryRequestSortItem
    from .landed_costs_list_inventory_request_sort_item_dir import LandedCostsListInventoryRequestSortItemDir
    from .landed_costs_list_inventory_response import LandedCostsListInventoryResponse
    from .landed_costs_list_inventory_response_rows_item import LandedCostsListInventoryResponseRowsItem
    from .landed_costs_list_inventory_response_rows_item_method import LandedCostsListInventoryResponseRowsItemMethod
    from .lots_get_inventory_response import LotsGetInventoryResponse
    from .lots_get_inventory_response_movements_item import LotsGetInventoryResponseMovementsItem
    from .lots_get_inventory_response_movements_item_direction import LotsGetInventoryResponseMovementsItemDirection
    from .lots_list_inventory_request_filter_item import LotsListInventoryRequestFilterItem
    from .lots_list_inventory_request_filter_item_op import LotsListInventoryRequestFilterItemOp
    from .lots_list_inventory_request_filter_item_value import LotsListInventoryRequestFilterItemValue
    from .lots_list_inventory_request_filter_item_value_three_item import (
        LotsListInventoryRequestFilterItemValueThreeItem,
    )
    from .lots_list_inventory_request_sort_item import LotsListInventoryRequestSortItem
    from .lots_list_inventory_request_sort_item_dir import LotsListInventoryRequestSortItemDir
    from .lots_list_inventory_response import LotsListInventoryResponse
    from .lots_list_inventory_response_rows_item import LotsListInventoryResponseRowsItem
    from .lots_update_inventory_response import LotsUpdateInventoryResponse
    from .reorder_rules_check_inventory_response import ReorderRulesCheckInventoryResponse
    from .reorder_rules_check_inventory_response_rows_item import ReorderRulesCheckInventoryResponseRowsItem
    from .reorder_rules_create_inventory_response import ReorderRulesCreateInventoryResponse
    from .reorder_rules_delete_inventory_response import ReorderRulesDeleteInventoryResponse
    from .reorder_rules_list_inventory_request_filter_item import ReorderRulesListInventoryRequestFilterItem
    from .reorder_rules_list_inventory_request_filter_item_op import ReorderRulesListInventoryRequestFilterItemOp
    from .reorder_rules_list_inventory_request_filter_item_value import ReorderRulesListInventoryRequestFilterItemValue
    from .reorder_rules_list_inventory_request_filter_item_value_three_item import (
        ReorderRulesListInventoryRequestFilterItemValueThreeItem,
    )
    from .reorder_rules_list_inventory_request_sort_item import ReorderRulesListInventoryRequestSortItem
    from .reorder_rules_list_inventory_request_sort_item_dir import ReorderRulesListInventoryRequestSortItemDir
    from .reorder_rules_list_inventory_response import ReorderRulesListInventoryResponse
    from .reorder_rules_list_inventory_response_rows_item import ReorderRulesListInventoryResponseRowsItem
    from .reorder_rules_update_inventory_response import ReorderRulesUpdateInventoryResponse
    from .settings_get_inventory_response import SettingsGetInventoryResponse
    from .settings_get_inventory_response_negative_stock_policy import SettingsGetInventoryResponseNegativeStockPolicy
    from .settings_update_inventory_request_negative_stock_policy import (
        SettingsUpdateInventoryRequestNegativeStockPolicy,
    )
    from .settings_update_inventory_response import SettingsUpdateInventoryResponse
    from .settings_update_inventory_response_negative_stock_policy import (
        SettingsUpdateInventoryResponseNegativeStockPolicy,
    )
    from .stock_levels_inventory_response import StockLevelsInventoryResponse
    from .stock_levels_inventory_response_rows_item import StockLevelsInventoryResponseRowsItem
    from .stock_movements_list_inventory_request_filter_item import StockMovementsListInventoryRequestFilterItem
    from .stock_movements_list_inventory_request_filter_item_op import StockMovementsListInventoryRequestFilterItemOp
    from .stock_movements_list_inventory_request_filter_item_value import (
        StockMovementsListInventoryRequestFilterItemValue,
    )
    from .stock_movements_list_inventory_request_filter_item_value_three_item import (
        StockMovementsListInventoryRequestFilterItemValueThreeItem,
    )
    from .stock_movements_list_inventory_request_sort_item import StockMovementsListInventoryRequestSortItem
    from .stock_movements_list_inventory_request_sort_item_dir import StockMovementsListInventoryRequestSortItemDir
    from .stock_movements_list_inventory_response import StockMovementsListInventoryResponse
    from .stock_movements_list_inventory_response_rows_item import StockMovementsListInventoryResponseRowsItem
    from .stock_movements_list_inventory_response_rows_item_direction import (
        StockMovementsListInventoryResponseRowsItemDirection,
    )
    from .stock_receive_inventory_response import StockReceiveInventoryResponse
    from .stock_take_inventory_request_lines_item import StockTakeInventoryRequestLinesItem
    from .stock_take_inventory_response import StockTakeInventoryResponse
    from .stock_take_inventory_response_rows_item import StockTakeInventoryResponseRowsItem
    from .stock_transfer_inventory_response import StockTransferInventoryResponse
    from .stock_write_off_inventory_response import StockWriteOffInventoryResponse
    from .warehouses_create_inventory_response import WarehousesCreateInventoryResponse
    from .warehouses_list_inventory_request_filter_item import WarehousesListInventoryRequestFilterItem
    from .warehouses_list_inventory_request_filter_item_op import WarehousesListInventoryRequestFilterItemOp
    from .warehouses_list_inventory_request_filter_item_value import WarehousesListInventoryRequestFilterItemValue
    from .warehouses_list_inventory_request_filter_item_value_three_item import (
        WarehousesListInventoryRequestFilterItemValueThreeItem,
    )
    from .warehouses_list_inventory_request_sort_item import WarehousesListInventoryRequestSortItem
    from .warehouses_list_inventory_request_sort_item_dir import WarehousesListInventoryRequestSortItemDir
    from .warehouses_list_inventory_response import WarehousesListInventoryResponse
    from .warehouses_list_inventory_response_rows_item import WarehousesListInventoryResponseRowsItem
_dynamic_imports: typing.Dict[str, str] = {
    "LandedCostsCreateInventoryRequestMethod": ".landed_costs_create_inventory_request_method",
    "LandedCostsCreateInventoryResponse": ".landed_costs_create_inventory_response",
    "LandedCostsCreateInventoryResponseLinesItem": ".landed_costs_create_inventory_response_lines_item",
    "LandedCostsCreateInventoryResponseMethod": ".landed_costs_create_inventory_response_method",
    "LandedCostsGetInventoryResponse": ".landed_costs_get_inventory_response",
    "LandedCostsGetInventoryResponseLinesItem": ".landed_costs_get_inventory_response_lines_item",
    "LandedCostsGetInventoryResponseMethod": ".landed_costs_get_inventory_response_method",
    "LandedCostsListInventoryRequestFilterItem": ".landed_costs_list_inventory_request_filter_item",
    "LandedCostsListInventoryRequestFilterItemOp": ".landed_costs_list_inventory_request_filter_item_op",
    "LandedCostsListInventoryRequestFilterItemValue": ".landed_costs_list_inventory_request_filter_item_value",
    "LandedCostsListInventoryRequestFilterItemValueThreeItem": ".landed_costs_list_inventory_request_filter_item_value_three_item",
    "LandedCostsListInventoryRequestSortItem": ".landed_costs_list_inventory_request_sort_item",
    "LandedCostsListInventoryRequestSortItemDir": ".landed_costs_list_inventory_request_sort_item_dir",
    "LandedCostsListInventoryResponse": ".landed_costs_list_inventory_response",
    "LandedCostsListInventoryResponseRowsItem": ".landed_costs_list_inventory_response_rows_item",
    "LandedCostsListInventoryResponseRowsItemMethod": ".landed_costs_list_inventory_response_rows_item_method",
    "LotsGetInventoryResponse": ".lots_get_inventory_response",
    "LotsGetInventoryResponseMovementsItem": ".lots_get_inventory_response_movements_item",
    "LotsGetInventoryResponseMovementsItemDirection": ".lots_get_inventory_response_movements_item_direction",
    "LotsListInventoryRequestFilterItem": ".lots_list_inventory_request_filter_item",
    "LotsListInventoryRequestFilterItemOp": ".lots_list_inventory_request_filter_item_op",
    "LotsListInventoryRequestFilterItemValue": ".lots_list_inventory_request_filter_item_value",
    "LotsListInventoryRequestFilterItemValueThreeItem": ".lots_list_inventory_request_filter_item_value_three_item",
    "LotsListInventoryRequestSortItem": ".lots_list_inventory_request_sort_item",
    "LotsListInventoryRequestSortItemDir": ".lots_list_inventory_request_sort_item_dir",
    "LotsListInventoryResponse": ".lots_list_inventory_response",
    "LotsListInventoryResponseRowsItem": ".lots_list_inventory_response_rows_item",
    "LotsUpdateInventoryResponse": ".lots_update_inventory_response",
    "ReorderRulesCheckInventoryResponse": ".reorder_rules_check_inventory_response",
    "ReorderRulesCheckInventoryResponseRowsItem": ".reorder_rules_check_inventory_response_rows_item",
    "ReorderRulesCreateInventoryResponse": ".reorder_rules_create_inventory_response",
    "ReorderRulesDeleteInventoryResponse": ".reorder_rules_delete_inventory_response",
    "ReorderRulesListInventoryRequestFilterItem": ".reorder_rules_list_inventory_request_filter_item",
    "ReorderRulesListInventoryRequestFilterItemOp": ".reorder_rules_list_inventory_request_filter_item_op",
    "ReorderRulesListInventoryRequestFilterItemValue": ".reorder_rules_list_inventory_request_filter_item_value",
    "ReorderRulesListInventoryRequestFilterItemValueThreeItem": ".reorder_rules_list_inventory_request_filter_item_value_three_item",
    "ReorderRulesListInventoryRequestSortItem": ".reorder_rules_list_inventory_request_sort_item",
    "ReorderRulesListInventoryRequestSortItemDir": ".reorder_rules_list_inventory_request_sort_item_dir",
    "ReorderRulesListInventoryResponse": ".reorder_rules_list_inventory_response",
    "ReorderRulesListInventoryResponseRowsItem": ".reorder_rules_list_inventory_response_rows_item",
    "ReorderRulesUpdateInventoryResponse": ".reorder_rules_update_inventory_response",
    "SettingsGetInventoryResponse": ".settings_get_inventory_response",
    "SettingsGetInventoryResponseNegativeStockPolicy": ".settings_get_inventory_response_negative_stock_policy",
    "SettingsUpdateInventoryRequestNegativeStockPolicy": ".settings_update_inventory_request_negative_stock_policy",
    "SettingsUpdateInventoryResponse": ".settings_update_inventory_response",
    "SettingsUpdateInventoryResponseNegativeStockPolicy": ".settings_update_inventory_response_negative_stock_policy",
    "StockLevelsInventoryResponse": ".stock_levels_inventory_response",
    "StockLevelsInventoryResponseRowsItem": ".stock_levels_inventory_response_rows_item",
    "StockMovementsListInventoryRequestFilterItem": ".stock_movements_list_inventory_request_filter_item",
    "StockMovementsListInventoryRequestFilterItemOp": ".stock_movements_list_inventory_request_filter_item_op",
    "StockMovementsListInventoryRequestFilterItemValue": ".stock_movements_list_inventory_request_filter_item_value",
    "StockMovementsListInventoryRequestFilterItemValueThreeItem": ".stock_movements_list_inventory_request_filter_item_value_three_item",
    "StockMovementsListInventoryRequestSortItem": ".stock_movements_list_inventory_request_sort_item",
    "StockMovementsListInventoryRequestSortItemDir": ".stock_movements_list_inventory_request_sort_item_dir",
    "StockMovementsListInventoryResponse": ".stock_movements_list_inventory_response",
    "StockMovementsListInventoryResponseRowsItem": ".stock_movements_list_inventory_response_rows_item",
    "StockMovementsListInventoryResponseRowsItemDirection": ".stock_movements_list_inventory_response_rows_item_direction",
    "StockReceiveInventoryResponse": ".stock_receive_inventory_response",
    "StockTakeInventoryRequestLinesItem": ".stock_take_inventory_request_lines_item",
    "StockTakeInventoryResponse": ".stock_take_inventory_response",
    "StockTakeInventoryResponseRowsItem": ".stock_take_inventory_response_rows_item",
    "StockTransferInventoryResponse": ".stock_transfer_inventory_response",
    "StockWriteOffInventoryResponse": ".stock_write_off_inventory_response",
    "WarehousesCreateInventoryResponse": ".warehouses_create_inventory_response",
    "WarehousesListInventoryRequestFilterItem": ".warehouses_list_inventory_request_filter_item",
    "WarehousesListInventoryRequestFilterItemOp": ".warehouses_list_inventory_request_filter_item_op",
    "WarehousesListInventoryRequestFilterItemValue": ".warehouses_list_inventory_request_filter_item_value",
    "WarehousesListInventoryRequestFilterItemValueThreeItem": ".warehouses_list_inventory_request_filter_item_value_three_item",
    "WarehousesListInventoryRequestSortItem": ".warehouses_list_inventory_request_sort_item",
    "WarehousesListInventoryRequestSortItemDir": ".warehouses_list_inventory_request_sort_item_dir",
    "WarehousesListInventoryResponse": ".warehouses_list_inventory_response",
    "WarehousesListInventoryResponseRowsItem": ".warehouses_list_inventory_response_rows_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "LandedCostsCreateInventoryRequestMethod",
    "LandedCostsCreateInventoryResponse",
    "LandedCostsCreateInventoryResponseLinesItem",
    "LandedCostsCreateInventoryResponseMethod",
    "LandedCostsGetInventoryResponse",
    "LandedCostsGetInventoryResponseLinesItem",
    "LandedCostsGetInventoryResponseMethod",
    "LandedCostsListInventoryRequestFilterItem",
    "LandedCostsListInventoryRequestFilterItemOp",
    "LandedCostsListInventoryRequestFilterItemValue",
    "LandedCostsListInventoryRequestFilterItemValueThreeItem",
    "LandedCostsListInventoryRequestSortItem",
    "LandedCostsListInventoryRequestSortItemDir",
    "LandedCostsListInventoryResponse",
    "LandedCostsListInventoryResponseRowsItem",
    "LandedCostsListInventoryResponseRowsItemMethod",
    "LotsGetInventoryResponse",
    "LotsGetInventoryResponseMovementsItem",
    "LotsGetInventoryResponseMovementsItemDirection",
    "LotsListInventoryRequestFilterItem",
    "LotsListInventoryRequestFilterItemOp",
    "LotsListInventoryRequestFilterItemValue",
    "LotsListInventoryRequestFilterItemValueThreeItem",
    "LotsListInventoryRequestSortItem",
    "LotsListInventoryRequestSortItemDir",
    "LotsListInventoryResponse",
    "LotsListInventoryResponseRowsItem",
    "LotsUpdateInventoryResponse",
    "ReorderRulesCheckInventoryResponse",
    "ReorderRulesCheckInventoryResponseRowsItem",
    "ReorderRulesCreateInventoryResponse",
    "ReorderRulesDeleteInventoryResponse",
    "ReorderRulesListInventoryRequestFilterItem",
    "ReorderRulesListInventoryRequestFilterItemOp",
    "ReorderRulesListInventoryRequestFilterItemValue",
    "ReorderRulesListInventoryRequestFilterItemValueThreeItem",
    "ReorderRulesListInventoryRequestSortItem",
    "ReorderRulesListInventoryRequestSortItemDir",
    "ReorderRulesListInventoryResponse",
    "ReorderRulesListInventoryResponseRowsItem",
    "ReorderRulesUpdateInventoryResponse",
    "SettingsGetInventoryResponse",
    "SettingsGetInventoryResponseNegativeStockPolicy",
    "SettingsUpdateInventoryRequestNegativeStockPolicy",
    "SettingsUpdateInventoryResponse",
    "SettingsUpdateInventoryResponseNegativeStockPolicy",
    "StockLevelsInventoryResponse",
    "StockLevelsInventoryResponseRowsItem",
    "StockMovementsListInventoryRequestFilterItem",
    "StockMovementsListInventoryRequestFilterItemOp",
    "StockMovementsListInventoryRequestFilterItemValue",
    "StockMovementsListInventoryRequestFilterItemValueThreeItem",
    "StockMovementsListInventoryRequestSortItem",
    "StockMovementsListInventoryRequestSortItemDir",
    "StockMovementsListInventoryResponse",
    "StockMovementsListInventoryResponseRowsItem",
    "StockMovementsListInventoryResponseRowsItemDirection",
    "StockReceiveInventoryResponse",
    "StockTakeInventoryRequestLinesItem",
    "StockTakeInventoryResponse",
    "StockTakeInventoryResponseRowsItem",
    "StockTransferInventoryResponse",
    "StockWriteOffInventoryResponse",
    "WarehousesCreateInventoryResponse",
    "WarehousesListInventoryRequestFilterItem",
    "WarehousesListInventoryRequestFilterItemOp",
    "WarehousesListInventoryRequestFilterItemValue",
    "WarehousesListInventoryRequestFilterItemValueThreeItem",
    "WarehousesListInventoryRequestSortItem",
    "WarehousesListInventoryRequestSortItemDir",
    "WarehousesListInventoryResponse",
    "WarehousesListInventoryResponseRowsItem",
]
