# This file was auto-generated by Fern from our API Definition.

import typing

from .landed_costs_list_inventory_request_filter_item_value_three_item import (
    LandedCostsListInventoryRequestFilterItemValueThreeItem,
)

LandedCostsListInventoryRequestFilterItemValue = typing.Union[
    str, float, bool, typing.List[LandedCostsListInventoryRequestFilterItemValueThreeItem]
]
