# This file was auto-generated by Fern from our API Definition.

import typing

from .stock_movements_list_inventory_request_filter_item_value_three_item import (
    StockMovementsListInventoryRequestFilterItemValueThreeItem,
)

StockMovementsListInventoryRequestFilterItemValue = typing.Union[
    str, float, bool, typing.List[StockMovementsListInventoryRequestFilterItemValueThreeItem]
]
