# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .update_platform_sellers_response_activities_item_activity import (
    UpdatePlatformSellersResponseActivitiesItemActivity,
)
from .update_platform_sellers_response_activities_item_property_address import (
    UpdatePlatformSellersResponseActivitiesItemPropertyAddress,
)
from .update_platform_sellers_response_activities_item_property_type import (
    UpdatePlatformSellersResponseActivitiesItemPropertyType,
)


class UpdatePlatformSellersResponseActivitiesItem(UniversalBaseModel):
    year: int
    activity: UpdatePlatformSellersResponseActivitiesItemActivity
    property_address: typing_extensions.Annotated[
        typing.Optional[UpdatePlatformSellersResponseActivitiesItemPropertyAddress],
        FieldMetadata(alias="propertyAddress"),
        pydantic.Field(alias="propertyAddress"),
    ] = None
    land_registration_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="landRegistrationNumber"),
        pydantic.Field(alias="landRegistrationNumber"),
    ] = None
    property_type: typing_extensions.Annotated[
        typing.Optional[UpdatePlatformSellersResponseActivitiesItemPropertyType],
        FieldMetadata(alias="propertyType"),
        pydantic.Field(alias="propertyType"),
    ] = None
    other_property_type: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="otherPropertyType"), pydantic.Field(alias="otherPropertyType")
    ] = None
    rented_days: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="rentedDays"), pydantic.Field(alias="rentedDays")
    ] = None
    consideration: typing.List[str]
    fees: typing.List[str]
    taxes: typing.List[str]
    number_of_activities: typing_extensions.Annotated[
        typing.List[int], FieldMetadata(alias="numberOfActivities"), pydantic.Field(alias="numberOfActivities")
    ]
    id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
