# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class PostV1AgreementsAgreementsUpdateResponseItemsItem(UniversalBaseModel):
    id: str
    item_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="itemId"), pydantic.Field(alias="itemId")
    ] = None
    description: str
    quantity: typing.Optional[str] = None
    unit_price: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="unitPrice"), pydantic.Field(alias="unitPrice")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
