# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_v1payroll_schedules_list_response_rows_item import PostV1PayrollSchedulesListResponseRowsItem


class PostV1PayrollSchedulesListResponse(UniversalBaseModel):
    rows: typing.List[PostV1PayrollSchedulesListResponseRowsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
