# This file was auto-generated by Fern from our API Definition.

import typing

RunsApprovePayrollResponseComponentTotalsItemKind = typing.Union[
    typing.Literal["allowance", "employee_tax", "employee_contribution", "employer_contribution", "employer_payment"],
    typing.Any,
]
