# This file was auto-generated by Fern from our API Definition.

import typing

PostV1ConsolidationMembersAddResponseMethod = typing.Union[typing.Literal["full", "proportional", "equity"], typing.Any]
