# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .report_consolidation_response_cash_flow import ReportConsolidationResponseCashFlow
from .report_consolidation_response_category import ReportConsolidationResponseCategory
from .report_consolidation_response_eliminations import ReportConsolidationResponseEliminations
from .report_consolidation_response_equity_method import ReportConsolidationResponseEquityMethod
from .report_consolidation_response_intercompany_candidates_item import (
    ReportConsolidationResponseIntercompanyCandidatesItem,
)
from .report_consolidation_response_members_item import ReportConsolidationResponseMembersItem
from .report_consolidation_response_non_controlling_interest import ReportConsolidationResponseNonControllingInterest
from .report_consolidation_response_statements import ReportConsolidationResponseStatements
from .report_consolidation_response_trial_balance_item import ReportConsolidationResponseTrialBalanceItem


class ReportConsolidationResponse(UniversalBaseModel):
    presentation_currency: typing_extensions.Annotated[
        str, FieldMetadata(alias="presentationCurrency"), pydantic.Field(alias="presentationCurrency")
    ]
    from_date: typing_extensions.Annotated[dt.date, FieldMetadata(alias="fromDate"), pydantic.Field(alias="fromDate")]
    to_date: typing_extensions.Annotated[dt.date, FieldMetadata(alias="toDate"), pydantic.Field(alias="toDate")]
    category: ReportConsolidationResponseCategory
    statements: ReportConsolidationResponseStatements
    trial_balance: typing_extensions.Annotated[
        typing.List[ReportConsolidationResponseTrialBalanceItem],
        FieldMetadata(alias="trialBalance"),
        pydantic.Field(alias="trialBalance"),
    ]
    non_controlling_interest: typing_extensions.Annotated[
        ReportConsolidationResponseNonControllingInterest,
        FieldMetadata(alias="nonControllingInterest"),
        pydantic.Field(alias="nonControllingInterest"),
    ]
    equity_method: typing_extensions.Annotated[
        ReportConsolidationResponseEquityMethod,
        FieldMetadata(alias="equityMethod"),
        pydantic.Field(alias="equityMethod"),
    ]
    members: typing.List[ReportConsolidationResponseMembersItem]
    eliminations: ReportConsolidationResponseEliminations
    cash_flow: typing_extensions.Annotated[
        ReportConsolidationResponseCashFlow, FieldMetadata(alias="cashFlow"), pydantic.Field(alias="cashFlow")
    ]
    intercompany_candidates: typing_extensions.Annotated[
        typing.List[ReportConsolidationResponseIntercompanyCandidatesItem],
        FieldMetadata(alias="intercompanyCandidates"),
        pydantic.Field(alias="intercompanyCandidates"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
