# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .devices_create_pos_response import DevicesCreatePosResponse
    from .devices_list_pos_request_filter_item import DevicesListPosRequestFilterItem
    from .devices_list_pos_request_filter_item_op import DevicesListPosRequestFilterItemOp
    from .devices_list_pos_request_filter_item_value import DevicesListPosRequestFilterItemValue
    from .devices_list_pos_request_filter_item_value_three_item import DevicesListPosRequestFilterItemValueThreeItem
    from .devices_list_pos_request_sort_item import DevicesListPosRequestSortItem
    from .devices_list_pos_request_sort_item_dir import DevicesListPosRequestSortItemDir
    from .devices_list_pos_response import DevicesListPosResponse
    from .devices_list_pos_response_rows_item import DevicesListPosResponseRowsItem
    from .devices_update_pos_response import DevicesUpdatePosResponse
    from .reports_create_pos_request_item_lines_item import ReportsCreatePosRequestItemLinesItem
    from .reports_create_pos_request_vat_lines_item import ReportsCreatePosRequestVatLinesItem
    from .reports_create_pos_response import ReportsCreatePosResponse
    from .reports_create_pos_response_vat_lines_item import ReportsCreatePosResponseVatLinesItem
    from .reports_get_pos_response import ReportsGetPosResponse
    from .reports_get_pos_response_vat_lines_item import ReportsGetPosResponseVatLinesItem
    from .reports_list_pos_request_filter_item import ReportsListPosRequestFilterItem
    from .reports_list_pos_request_filter_item_op import ReportsListPosRequestFilterItemOp
    from .reports_list_pos_request_filter_item_value import ReportsListPosRequestFilterItemValue
    from .reports_list_pos_request_filter_item_value_three_item import ReportsListPosRequestFilterItemValueThreeItem
    from .reports_list_pos_request_sort_item import ReportsListPosRequestSortItem
    from .reports_list_pos_request_sort_item_dir import ReportsListPosRequestSortItemDir
    from .reports_list_pos_response import ReportsListPosResponse
    from .reports_list_pos_response_rows_item import ReportsListPosResponseRowsItem
_dynamic_imports: typing.Dict[str, str] = {
    "DevicesCreatePosResponse": ".devices_create_pos_response",
    "DevicesListPosRequestFilterItem": ".devices_list_pos_request_filter_item",
    "DevicesListPosRequestFilterItemOp": ".devices_list_pos_request_filter_item_op",
    "DevicesListPosRequestFilterItemValue": ".devices_list_pos_request_filter_item_value",
    "DevicesListPosRequestFilterItemValueThreeItem": ".devices_list_pos_request_filter_item_value_three_item",
    "DevicesListPosRequestSortItem": ".devices_list_pos_request_sort_item",
    "DevicesListPosRequestSortItemDir": ".devices_list_pos_request_sort_item_dir",
    "DevicesListPosResponse": ".devices_list_pos_response",
    "DevicesListPosResponseRowsItem": ".devices_list_pos_response_rows_item",
    "DevicesUpdatePosResponse": ".devices_update_pos_response",
    "ReportsCreatePosRequestItemLinesItem": ".reports_create_pos_request_item_lines_item",
    "ReportsCreatePosRequestVatLinesItem": ".reports_create_pos_request_vat_lines_item",
    "ReportsCreatePosResponse": ".reports_create_pos_response",
    "ReportsCreatePosResponseVatLinesItem": ".reports_create_pos_response_vat_lines_item",
    "ReportsGetPosResponse": ".reports_get_pos_response",
    "ReportsGetPosResponseVatLinesItem": ".reports_get_pos_response_vat_lines_item",
    "ReportsListPosRequestFilterItem": ".reports_list_pos_request_filter_item",
    "ReportsListPosRequestFilterItemOp": ".reports_list_pos_request_filter_item_op",
    "ReportsListPosRequestFilterItemValue": ".reports_list_pos_request_filter_item_value",
    "ReportsListPosRequestFilterItemValueThreeItem": ".reports_list_pos_request_filter_item_value_three_item",
    "ReportsListPosRequestSortItem": ".reports_list_pos_request_sort_item",
    "ReportsListPosRequestSortItemDir": ".reports_list_pos_request_sort_item_dir",
    "ReportsListPosResponse": ".reports_list_pos_response",
    "ReportsListPosResponseRowsItem": ".reports_list_pos_response_rows_item",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "DevicesCreatePosResponse",
    "DevicesListPosRequestFilterItem",
    "DevicesListPosRequestFilterItemOp",
    "DevicesListPosRequestFilterItemValue",
    "DevicesListPosRequestFilterItemValueThreeItem",
    "DevicesListPosRequestSortItem",
    "DevicesListPosRequestSortItemDir",
    "DevicesListPosResponse",
    "DevicesListPosResponseRowsItem",
    "DevicesUpdatePosResponse",
    "ReportsCreatePosRequestItemLinesItem",
    "ReportsCreatePosRequestVatLinesItem",
    "ReportsCreatePosResponse",
    "ReportsCreatePosResponseVatLinesItem",
    "ReportsGetPosResponse",
    "ReportsGetPosResponseVatLinesItem",
    "ReportsListPosRequestFilterItem",
    "ReportsListPosRequestFilterItemOp",
    "ReportsListPosRequestFilterItemValue",
    "ReportsListPosRequestFilterItemValueThreeItem",
    "ReportsListPosRequestSortItem",
    "ReportsListPosRequestSortItemDir",
    "ReportsListPosResponse",
    "ReportsListPosResponseRowsItem",
]
