# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .receipts_create_pos_response_lines_item import ReceiptsCreatePosResponseLinesItem


class ReceiptsCreatePosResponse(UniversalBaseModel):
    id: str
    shift_id: typing_extensions.Annotated[str, FieldMetadata(alias="shiftId"), pydantic.Field(alias="shiftId")]
    number: int
    net_total: typing_extensions.Annotated[str, FieldMetadata(alias="netTotal"), pydantic.Field(alias="netTotal")]
    vat_total: typing_extensions.Annotated[str, FieldMetadata(alias="vatTotal"), pydantic.Field(alias="vatTotal")]
    gross_total: typing_extensions.Annotated[str, FieldMetadata(alias="grossTotal"), pydantic.Field(alias="grossTotal")]
    cash_amount: typing_extensions.Annotated[str, FieldMetadata(alias="cashAmount"), pydantic.Field(alias="cashAmount")]
    card_amount: typing_extensions.Annotated[str, FieldMetadata(alias="cardAmount"), pydantic.Field(alias="cardAmount")]
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    lines: typing.List[ReceiptsCreatePosResponseLinesItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
