# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class PostV1AccountExportResponseBilling(UniversalBaseModel):
    status: str
    plan: str
    balance_cents: typing_extensions.Annotated[
        int, FieldMetadata(alias="balanceCents"), pydantic.Field(alias="balanceCents")
    ]
    trial_ends_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="trialEndsAt"), pydantic.Field(alias="trialEndsAt")
    ] = None
    first_top_up_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="firstTopUpAt"), pydantic.Field(alias="firstTopUpAt")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
