# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .debt_reminders_list_partners_request_sort_item_dir import DebtRemindersListPartnersRequestSortItemDir


class DebtRemindersListPartnersRequestSortItem(UniversalBaseModel):
    field: str
    dir: typing.Optional[DebtRemindersListPartnersRequestSortItemDir] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
