# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .post_v1partners_bank_accounts_list_request_filter_item_op import PostV1PartnersBankAccountsListRequestFilterItemOp
from .post_v1partners_bank_accounts_list_request_filter_item_value import (
    PostV1PartnersBankAccountsListRequestFilterItemValue,
)


class PostV1PartnersBankAccountsListRequestFilterItem(UniversalBaseModel):
    field: str
    op: PostV1PartnersBankAccountsListRequestFilterItemOp
    value: PostV1PartnersBankAccountsListRequestFilterItemValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
