# This file was auto-generated by Fern from our API Definition.

import typing

PostV1PartnersVatReviewsResolveRequestResolution = typing.Union[
    typing.Literal["confirmed_valid", "confirmed_invalid", "dismissed"], typing.Any
]
