# This file was auto-generated by Fern from our API Definition.

import typing

VatReviewsResolvePartnersResponseResolution = typing.Union[
    typing.Literal["confirmed_valid", "confirmed_invalid", "dismissed", "revalidated", "superseded"], typing.Any
]
