# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .vat_reviews_resolve_partners_response_details import VatReviewsResolvePartnersResponseDetails
from .vat_reviews_resolve_partners_response_reason import VatReviewsResolvePartnersResponseReason
from .vat_reviews_resolve_partners_response_resolution import VatReviewsResolvePartnersResponseResolution
from .vat_reviews_resolve_partners_response_status import VatReviewsResolvePartnersResponseStatus


class VatReviewsResolvePartnersResponse(UniversalBaseModel):
    id: str
    partner_id: typing_extensions.Annotated[str, FieldMetadata(alias="partnerId"), pydantic.Field(alias="partnerId")]
    vat_code: typing_extensions.Annotated[str, FieldMetadata(alias="vatCode"), pydantic.Field(alias="vatCode")]
    reason: VatReviewsResolvePartnersResponseReason
    status: VatReviewsResolvePartnersResponseStatus
    resolution: typing.Optional[VatReviewsResolvePartnersResponseResolution] = None
    resolution_note: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="resolutionNote"), pydantic.Field(alias="resolutionNote")
    ] = None
    details: typing.Optional[VatReviewsResolvePartnersResponseDetails] = None
    resolved_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="resolvedAt"), pydantic.Field(alias="resolvedAt")
    ] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
