# This file was auto-generated by Fern from our API Definition.

import typing

from .cost_center_groups_list_ledger_request_filter_item_value_three_item import (
    CostCenterGroupsListLedgerRequestFilterItemValueThreeItem,
)

CostCenterGroupsListLedgerRequestFilterItemValue = typing.Union[
    str, float, bool, typing.List[CostCenterGroupsListLedgerRequestFilterItemValueThreeItem]
]
