# This file was auto-generated by Fern from our API Definition.

import typing

PostV1LedgerOwnersListResponseRowsItemPartnerLiability = typing.Union[typing.Literal["general", "limited"], typing.Any]
