# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_v1ledger_statement_rows_list_response_accounts_item_source import (
    PostV1LedgerStatementRowsListResponseAccountsItemSource,
)


class PostV1LedgerStatementRowsListResponseAccountsItem(UniversalBaseModel):
    code: str
    name: str
    type: str
    row_code: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="rowCode"), pydantic.Field(alias="rowCode")
    ] = None
    source: typing.Optional[PostV1LedgerStatementRowsListResponseAccountsItemSource] = None
    amount: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
