# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .per_diem_rates_list_hr_request_filter_item_op import PerDiemRatesListHrRequestFilterItemOp
from .per_diem_rates_list_hr_request_filter_item_value import PerDiemRatesListHrRequestFilterItemValue


class PerDiemRatesListHrRequestFilterItem(UniversalBaseModel):
    field: str
    op: PerDiemRatesListHrRequestFilterItemOp
    value: PerDiemRatesListHrRequestFilterItemValue

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
