# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .post_v1hr_employees_update_response_address import PostV1HrEmployeesUpdateResponseAddress
from .post_v1hr_employees_update_response_status import PostV1HrEmployeesUpdateResponseStatus


class PostV1HrEmployeesUpdateResponse(UniversalBaseModel):
    id: str
    code: typing.Optional[str] = None
    first_name: typing_extensions.Annotated[str, FieldMetadata(alias="firstName"), pydantic.Field(alias="firstName")]
    last_name: typing_extensions.Annotated[str, FieldMetadata(alias="lastName"), pydantic.Field(alias="lastName")]
    personal_code: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="personalCode"), pydantic.Field(alias="personalCode")
    ] = None
    birth_date: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="birthDate"), pydantic.Field(alias="birthDate")
    ] = None
    email: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    address: typing.Optional[PostV1HrEmployeesUpdateResponseAddress] = None
    iban: typing.Optional[str] = None
    social_insurance_no: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="socialInsuranceNo"), pydantic.Field(alias="socialInsuranceNo")
    ] = None
    social_insurance_start: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="socialInsuranceStart"), pydantic.Field(alias="socialInsuranceStart")
    ] = None
    hire_date: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="hireDate"), pydantic.Field(alias="hireDate")
    ] = None
    termination_date: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="terminationDate"), pydantic.Field(alias="terminationDate")
    ] = None
    apply_npd: typing_extensions.Annotated[bool, FieldMetadata(alias="applyNpd"), pydantic.Field(alias="applyNpd")]
    npd_override: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="npdOverride"), pydantic.Field(alias="npdOverride")
    ] = None
    pension_accumulation: typing_extensions.Annotated[
        bool, FieldMetadata(alias="pensionAccumulation"), pydantic.Field(alias="pensionAccumulation")
    ]
    status: PostV1HrEmployeesUpdateResponseStatus
    notes: typing.Optional[str] = None
    created_at: typing_extensions.Annotated[str, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
