# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .boms_create_production_request_lines_item import BomsCreateProductionRequestLinesItem
    from .boms_create_production_response import BomsCreateProductionResponse
    from .boms_create_production_response_lines_item import BomsCreateProductionResponseLinesItem
    from .boms_get_production_response import BomsGetProductionResponse
    from .boms_get_production_response_lines_item import BomsGetProductionResponseLinesItem
    from .boms_list_production_request_filter_item import BomsListProductionRequestFilterItem
    from .boms_list_production_request_filter_item_op import BomsListProductionRequestFilterItemOp
    from .boms_list_production_request_filter_item_value import BomsListProductionRequestFilterItemValue
    from .boms_list_production_request_filter_item_value_three_item import (
        BomsListProductionRequestFilterItemValueThreeItem,
    )
    from .boms_list_production_request_sort_item import BomsListProductionRequestSortItem
    from .boms_list_production_request_sort_item_dir import BomsListProductionRequestSortItemDir
    from .boms_list_production_response import BomsListProductionResponse
    from .boms_list_production_response_rows_item import BomsListProductionResponseRowsItem
    from .maintenance_cancel_production_response import MaintenanceCancelProductionResponse
    from .maintenance_cancel_production_response_status import MaintenanceCancelProductionResponseStatus
    from .maintenance_cancel_production_response_type import MaintenanceCancelProductionResponseType
    from .maintenance_complete_production_response import MaintenanceCompleteProductionResponse
    from .maintenance_complete_production_response_status import MaintenanceCompleteProductionResponseStatus
    from .maintenance_complete_production_response_type import MaintenanceCompleteProductionResponseType
    from .maintenance_create_production_request_type import MaintenanceCreateProductionRequestType
    from .maintenance_create_production_response import MaintenanceCreateProductionResponse
    from .maintenance_create_production_response_status import MaintenanceCreateProductionResponseStatus
    from .maintenance_create_production_response_type import MaintenanceCreateProductionResponseType
    from .maintenance_list_production_request_filter_item import MaintenanceListProductionRequestFilterItem
    from .maintenance_list_production_request_filter_item_op import MaintenanceListProductionRequestFilterItemOp
    from .maintenance_list_production_request_filter_item_value import MaintenanceListProductionRequestFilterItemValue
    from .maintenance_list_production_request_filter_item_value_three_item import (
        MaintenanceListProductionRequestFilterItemValueThreeItem,
    )
    from .maintenance_list_production_request_sort_item import MaintenanceListProductionRequestSortItem
    from .maintenance_list_production_request_sort_item_dir import MaintenanceListProductionRequestSortItemDir
    from .maintenance_list_production_response import MaintenanceListProductionResponse
    from .maintenance_list_production_response_rows_item import MaintenanceListProductionResponseRowsItem
    from .maintenance_list_production_response_rows_item_status import MaintenanceListProductionResponseRowsItemStatus
    from .maintenance_list_production_response_rows_item_type import MaintenanceListProductionResponseRowsItemType
    from .orders_complete_production_response import OrdersCompleteProductionResponse
    from .orders_complete_production_response_status import OrdersCompleteProductionResponseStatus
    from .orders_complete_production_response_type import OrdersCompleteProductionResponseType
    from .orders_create_production_request_type import OrdersCreateProductionRequestType
    from .orders_create_production_response import OrdersCreateProductionResponse
    from .orders_create_production_response_operations_item import OrdersCreateProductionResponseOperationsItem
    from .orders_create_production_response_quality_checks_item import OrdersCreateProductionResponseQualityChecksItem
    from .orders_create_production_response_quality_checks_item_result import (
        OrdersCreateProductionResponseQualityChecksItemResult,
    )
    from .orders_create_production_response_status import OrdersCreateProductionResponseStatus
    from .orders_create_production_response_type import OrdersCreateProductionResponseType
    from .orders_get_production_response import OrdersGetProductionResponse
    from .orders_get_production_response_operations_item import OrdersGetProductionResponseOperationsItem
    from .orders_get_production_response_quality_checks_item import OrdersGetProductionResponseQualityChecksItem
    from .orders_get_production_response_quality_checks_item_result import (
        OrdersGetProductionResponseQualityChecksItemResult,
    )
    from .orders_get_production_response_status import OrdersGetProductionResponseStatus
    from .orders_get_production_response_type import OrdersGetProductionResponseType
    from .orders_list_production_request_filter_item import OrdersListProductionRequestFilterItem
    from .orders_list_production_request_filter_item_op import OrdersListProductionRequestFilterItemOp
    from .orders_list_production_request_filter_item_value import OrdersListProductionRequestFilterItemValue
    from .orders_list_production_request_filter_item_value_three_item import (
        OrdersListProductionRequestFilterItemValueThreeItem,
    )
    from .orders_list_production_request_sort_item import OrdersListProductionRequestSortItem
    from .orders_list_production_request_sort_item_dir import OrdersListProductionRequestSortItemDir
    from .orders_list_production_response import OrdersListProductionResponse
    from .orders_list_production_response_rows_item import OrdersListProductionResponseRowsItem
    from .orders_list_production_response_rows_item_status import OrdersListProductionResponseRowsItemStatus
    from .orders_list_production_response_rows_item_type import OrdersListProductionResponseRowsItemType
    from .orders_record_operation_production_response import OrdersRecordOperationProductionResponse
    from .quality_checks_add_production_response import QualityChecksAddProductionResponse
    from .quality_checks_add_production_response_result import QualityChecksAddProductionResponseResult
    from .quality_checks_list_production_request_filter_item import QualityChecksListProductionRequestFilterItem
    from .quality_checks_list_production_request_filter_item_op import QualityChecksListProductionRequestFilterItemOp
    from .quality_checks_list_production_request_filter_item_value import (
        QualityChecksListProductionRequestFilterItemValue,
    )
    from .quality_checks_list_production_request_filter_item_value_three_item import (
        QualityChecksListProductionRequestFilterItemValueThreeItem,
    )
    from .quality_checks_list_production_request_sort_item import QualityChecksListProductionRequestSortItem
    from .quality_checks_list_production_request_sort_item_dir import QualityChecksListProductionRequestSortItemDir
    from .quality_checks_list_production_response import QualityChecksListProductionResponse
    from .quality_checks_list_production_response_rows_item import QualityChecksListProductionResponseRowsItem
    from .quality_checks_list_production_response_rows_item_result import (
        QualityChecksListProductionResponseRowsItemResult,
    )
    from .quality_checks_record_production_request_result import QualityChecksRecordProductionRequestResult
    from .quality_checks_record_production_response import QualityChecksRecordProductionResponse
    from .quality_checks_record_production_response_result import QualityChecksRecordProductionResponseResult
    from .routings_create_production_request_operations_item import RoutingsCreateProductionRequestOperationsItem
    from .routings_create_production_response import RoutingsCreateProductionResponse
    from .routings_create_production_response_operations_item import RoutingsCreateProductionResponseOperationsItem
    from .routings_get_production_response import RoutingsGetProductionResponse
    from .routings_get_production_response_operations_item import RoutingsGetProductionResponseOperationsItem
    from .routings_list_production_request_filter_item import RoutingsListProductionRequestFilterItem
    from .routings_list_production_request_filter_item_op import RoutingsListProductionRequestFilterItemOp
    from .routings_list_production_request_filter_item_value import RoutingsListProductionRequestFilterItemValue
    from .routings_list_production_request_filter_item_value_three_item import (
        RoutingsListProductionRequestFilterItemValueThreeItem,
    )
    from .routings_list_production_request_sort_item import RoutingsListProductionRequestSortItem
    from .routings_list_production_request_sort_item_dir import RoutingsListProductionRequestSortItemDir
    from .routings_list_production_response import RoutingsListProductionResponse
    from .routings_list_production_response_rows_item import RoutingsListProductionResponseRowsItem
    from .work_centers_create_production_response import WorkCentersCreateProductionResponse
    from .work_centers_list_production_request_filter_item import WorkCentersListProductionRequestFilterItem
    from .work_centers_list_production_request_filter_item_op import WorkCentersListProductionRequestFilterItemOp
    from .work_centers_list_production_request_filter_item_value import WorkCentersListProductionRequestFilterItemValue
    from .work_centers_list_production_request_filter_item_value_three_item import (
        WorkCentersListProductionRequestFilterItemValueThreeItem,
    )
    from .work_centers_list_production_request_sort_item import WorkCentersListProductionRequestSortItem
    from .work_centers_list_production_request_sort_item_dir import WorkCentersListProductionRequestSortItemDir
    from .work_centers_list_production_response import WorkCentersListProductionResponse
    from .work_centers_list_production_response_rows_item import WorkCentersListProductionResponseRowsItem
    from .work_centers_update_production_response import WorkCentersUpdateProductionResponse
_dynamic_imports: typing.Dict[str, str] = {
    "BomsCreateProductionRequestLinesItem": ".boms_create_production_request_lines_item",
    "BomsCreateProductionResponse": ".boms_create_production_response",
    "BomsCreateProductionResponseLinesItem": ".boms_create_production_response_lines_item",
    "BomsGetProductionResponse": ".boms_get_production_response",
    "BomsGetProductionResponseLinesItem": ".boms_get_production_response_lines_item",
    "BomsListProductionRequestFilterItem": ".boms_list_production_request_filter_item",
    "BomsListProductionRequestFilterItemOp": ".boms_list_production_request_filter_item_op",
    "BomsListProductionRequestFilterItemValue": ".boms_list_production_request_filter_item_value",
    "BomsListProductionRequestFilterItemValueThreeItem": ".boms_list_production_request_filter_item_value_three_item",
    "BomsListProductionRequestSortItem": ".boms_list_production_request_sort_item",
    "BomsListProductionRequestSortItemDir": ".boms_list_production_request_sort_item_dir",
    "BomsListProductionResponse": ".boms_list_production_response",
    "BomsListProductionResponseRowsItem": ".boms_list_production_response_rows_item",
    "MaintenanceCancelProductionResponse": ".maintenance_cancel_production_response",
    "MaintenanceCancelProductionResponseStatus": ".maintenance_cancel_production_response_status",
    "MaintenanceCancelProductionResponseType": ".maintenance_cancel_production_response_type",
    "MaintenanceCompleteProductionResponse": ".maintenance_complete_production_response",
    "MaintenanceCompleteProductionResponseStatus": ".maintenance_complete_production_response_status",
    "MaintenanceCompleteProductionResponseType": ".maintenance_complete_production_response_type",
    "MaintenanceCreateProductionRequestType": ".maintenance_create_production_request_type",
    "MaintenanceCreateProductionResponse": ".maintenance_create_production_response",
    "MaintenanceCreateProductionResponseStatus": ".maintenance_create_production_response_status",
    "MaintenanceCreateProductionResponseType": ".maintenance_create_production_response_type",
    "MaintenanceListProductionRequestFilterItem": ".maintenance_list_production_request_filter_item",
    "MaintenanceListProductionRequestFilterItemOp": ".maintenance_list_production_request_filter_item_op",
    "MaintenanceListProductionRequestFilterItemValue": ".maintenance_list_production_request_filter_item_value",
    "MaintenanceListProductionRequestFilterItemValueThreeItem": ".maintenance_list_production_request_filter_item_value_three_item",
    "MaintenanceListProductionRequestSortItem": ".maintenance_list_production_request_sort_item",
    "MaintenanceListProductionRequestSortItemDir": ".maintenance_list_production_request_sort_item_dir",
    "MaintenanceListProductionResponse": ".maintenance_list_production_response",
    "MaintenanceListProductionResponseRowsItem": ".maintenance_list_production_response_rows_item",
    "MaintenanceListProductionResponseRowsItemStatus": ".maintenance_list_production_response_rows_item_status",
    "MaintenanceListProductionResponseRowsItemType": ".maintenance_list_production_response_rows_item_type",
    "OrdersCompleteProductionResponse": ".orders_complete_production_response",
    "OrdersCompleteProductionResponseStatus": ".orders_complete_production_response_status",
    "OrdersCompleteProductionResponseType": ".orders_complete_production_response_type",
    "OrdersCreateProductionRequestType": ".orders_create_production_request_type",
    "OrdersCreateProductionResponse": ".orders_create_production_response",
    "OrdersCreateProductionResponseOperationsItem": ".orders_create_production_response_operations_item",
    "OrdersCreateProductionResponseQualityChecksItem": ".orders_create_production_response_quality_checks_item",
    "OrdersCreateProductionResponseQualityChecksItemResult": ".orders_create_production_response_quality_checks_item_result",
    "OrdersCreateProductionResponseStatus": ".orders_create_production_response_status",
    "OrdersCreateProductionResponseType": ".orders_create_production_response_type",
    "OrdersGetProductionResponse": ".orders_get_production_response",
    "OrdersGetProductionResponseOperationsItem": ".orders_get_production_response_operations_item",
    "OrdersGetProductionResponseQualityChecksItem": ".orders_get_production_response_quality_checks_item",
    "OrdersGetProductionResponseQualityChecksItemResult": ".orders_get_production_response_quality_checks_item_result",
    "OrdersGetProductionResponseStatus": ".orders_get_production_response_status",
    "OrdersGetProductionResponseType": ".orders_get_production_response_type",
    "OrdersListProductionRequestFilterItem": ".orders_list_production_request_filter_item",
    "OrdersListProductionRequestFilterItemOp": ".orders_list_production_request_filter_item_op",
    "OrdersListProductionRequestFilterItemValue": ".orders_list_production_request_filter_item_value",
    "OrdersListProductionRequestFilterItemValueThreeItem": ".orders_list_production_request_filter_item_value_three_item",
    "OrdersListProductionRequestSortItem": ".orders_list_production_request_sort_item",
    "OrdersListProductionRequestSortItemDir": ".orders_list_production_request_sort_item_dir",
    "OrdersListProductionResponse": ".orders_list_production_response",
    "OrdersListProductionResponseRowsItem": ".orders_list_production_response_rows_item",
    "OrdersListProductionResponseRowsItemStatus": ".orders_list_production_response_rows_item_status",
    "OrdersListProductionResponseRowsItemType": ".orders_list_production_response_rows_item_type",
    "OrdersRecordOperationProductionResponse": ".orders_record_operation_production_response",
    "QualityChecksAddProductionResponse": ".quality_checks_add_production_response",
    "QualityChecksAddProductionResponseResult": ".quality_checks_add_production_response_result",
    "QualityChecksListProductionRequestFilterItem": ".quality_checks_list_production_request_filter_item",
    "QualityChecksListProductionRequestFilterItemOp": ".quality_checks_list_production_request_filter_item_op",
    "QualityChecksListProductionRequestFilterItemValue": ".quality_checks_list_production_request_filter_item_value",
    "QualityChecksListProductionRequestFilterItemValueThreeItem": ".quality_checks_list_production_request_filter_item_value_three_item",
    "QualityChecksListProductionRequestSortItem": ".quality_checks_list_production_request_sort_item",
    "QualityChecksListProductionRequestSortItemDir": ".quality_checks_list_production_request_sort_item_dir",
    "QualityChecksListProductionResponse": ".quality_checks_list_production_response",
    "QualityChecksListProductionResponseRowsItem": ".quality_checks_list_production_response_rows_item",
    "QualityChecksListProductionResponseRowsItemResult": ".quality_checks_list_production_response_rows_item_result",
    "QualityChecksRecordProductionRequestResult": ".quality_checks_record_production_request_result",
    "QualityChecksRecordProductionResponse": ".quality_checks_record_production_response",
    "QualityChecksRecordProductionResponseResult": ".quality_checks_record_production_response_result",
    "RoutingsCreateProductionRequestOperationsItem": ".routings_create_production_request_operations_item",
    "RoutingsCreateProductionResponse": ".routings_create_production_response",
    "RoutingsCreateProductionResponseOperationsItem": ".routings_create_production_response_operations_item",
    "RoutingsGetProductionResponse": ".routings_get_production_response",
    "RoutingsGetProductionResponseOperationsItem": ".routings_get_production_response_operations_item",
    "RoutingsListProductionRequestFilterItem": ".routings_list_production_request_filter_item",
    "RoutingsListProductionRequestFilterItemOp": ".routings_list_production_request_filter_item_op",
    "RoutingsListProductionRequestFilterItemValue": ".routings_list_production_request_filter_item_value",
    "RoutingsListProductionRequestFilterItemValueThreeItem": ".routings_list_production_request_filter_item_value_three_item",
    "RoutingsListProductionRequestSortItem": ".routings_list_production_request_sort_item",
    "RoutingsListProductionRequestSortItemDir": ".routings_list_production_request_sort_item_dir",
    "RoutingsListProductionResponse": ".routings_list_production_response",
    "RoutingsListProductionResponseRowsItem": ".routings_list_production_response_rows_item",
    "WorkCentersCreateProductionResponse": ".work_centers_create_production_response",
    "WorkCentersListProductionRequestFilterItem": ".work_centers_list_production_request_filter_item",
    "WorkCentersListProductionRequestFilterItemOp": ".work_centers_list_production_request_filter_item_op",
    "WorkCentersListProductionRequestFilterItemValue": ".work_centers_list_production_request_filter_item_value",
    "WorkCentersListProductionRequestFilterItemValueThreeItem": ".work_centers_list_production_request_filter_item_value_three_item",
    "WorkCentersListProductionRequestSortItem": ".work_centers_list_production_request_sort_item",
    "WorkCentersListProductionRequestSortItemDir": ".work_centers_list_production_request_sort_item_dir",
    "WorkCentersListProductionResponse": ".work_centers_list_production_response",
    "WorkCentersListProductionResponseRowsItem": ".work_centers_list_production_response_rows_item",
    "WorkCentersUpdateProductionResponse": ".work_centers_update_production_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "BomsCreateProductionRequestLinesItem",
    "BomsCreateProductionResponse",
    "BomsCreateProductionResponseLinesItem",
    "BomsGetProductionResponse",
    "BomsGetProductionResponseLinesItem",
    "BomsListProductionRequestFilterItem",
    "BomsListProductionRequestFilterItemOp",
    "BomsListProductionRequestFilterItemValue",
    "BomsListProductionRequestFilterItemValueThreeItem",
    "BomsListProductionRequestSortItem",
    "BomsListProductionRequestSortItemDir",
    "BomsListProductionResponse",
    "BomsListProductionResponseRowsItem",
    "MaintenanceCancelProductionResponse",
    "MaintenanceCancelProductionResponseStatus",
    "MaintenanceCancelProductionResponseType",
    "MaintenanceCompleteProductionResponse",
    "MaintenanceCompleteProductionResponseStatus",
    "MaintenanceCompleteProductionResponseType",
    "MaintenanceCreateProductionRequestType",
    "MaintenanceCreateProductionResponse",
    "MaintenanceCreateProductionResponseStatus",
    "MaintenanceCreateProductionResponseType",
    "MaintenanceListProductionRequestFilterItem",
    "MaintenanceListProductionRequestFilterItemOp",
    "MaintenanceListProductionRequestFilterItemValue",
    "MaintenanceListProductionRequestFilterItemValueThreeItem",
    "MaintenanceListProductionRequestSortItem",
    "MaintenanceListProductionRequestSortItemDir",
    "MaintenanceListProductionResponse",
    "MaintenanceListProductionResponseRowsItem",
    "MaintenanceListProductionResponseRowsItemStatus",
    "MaintenanceListProductionResponseRowsItemType",
    "OrdersCompleteProductionResponse",
    "OrdersCompleteProductionResponseStatus",
    "OrdersCompleteProductionResponseType",
    "OrdersCreateProductionRequestType",
    "OrdersCreateProductionResponse",
    "OrdersCreateProductionResponseOperationsItem",
    "OrdersCreateProductionResponseQualityChecksItem",
    "OrdersCreateProductionResponseQualityChecksItemResult",
    "OrdersCreateProductionResponseStatus",
    "OrdersCreateProductionResponseType",
    "OrdersGetProductionResponse",
    "OrdersGetProductionResponseOperationsItem",
    "OrdersGetProductionResponseQualityChecksItem",
    "OrdersGetProductionResponseQualityChecksItemResult",
    "OrdersGetProductionResponseStatus",
    "OrdersGetProductionResponseType",
    "OrdersListProductionRequestFilterItem",
    "OrdersListProductionRequestFilterItemOp",
    "OrdersListProductionRequestFilterItemValue",
    "OrdersListProductionRequestFilterItemValueThreeItem",
    "OrdersListProductionRequestSortItem",
    "OrdersListProductionRequestSortItemDir",
    "OrdersListProductionResponse",
    "OrdersListProductionResponseRowsItem",
    "OrdersListProductionResponseRowsItemStatus",
    "OrdersListProductionResponseRowsItemType",
    "OrdersRecordOperationProductionResponse",
    "QualityChecksAddProductionResponse",
    "QualityChecksAddProductionResponseResult",
    "QualityChecksListProductionRequestFilterItem",
    "QualityChecksListProductionRequestFilterItemOp",
    "QualityChecksListProductionRequestFilterItemValue",
    "QualityChecksListProductionRequestFilterItemValueThreeItem",
    "QualityChecksListProductionRequestSortItem",
    "QualityChecksListProductionRequestSortItemDir",
    "QualityChecksListProductionResponse",
    "QualityChecksListProductionResponseRowsItem",
    "QualityChecksListProductionResponseRowsItemResult",
    "QualityChecksRecordProductionRequestResult",
    "QualityChecksRecordProductionResponse",
    "QualityChecksRecordProductionResponseResult",
    "RoutingsCreateProductionRequestOperationsItem",
    "RoutingsCreateProductionResponse",
    "RoutingsCreateProductionResponseOperationsItem",
    "RoutingsGetProductionResponse",
    "RoutingsGetProductionResponseOperationsItem",
    "RoutingsListProductionRequestFilterItem",
    "RoutingsListProductionRequestFilterItemOp",
    "RoutingsListProductionRequestFilterItemValue",
    "RoutingsListProductionRequestFilterItemValueThreeItem",
    "RoutingsListProductionRequestSortItem",
    "RoutingsListProductionRequestSortItemDir",
    "RoutingsListProductionResponse",
    "RoutingsListProductionResponseRowsItem",
    "WorkCentersCreateProductionResponse",
    "WorkCentersListProductionRequestFilterItem",
    "WorkCentersListProductionRequestFilterItemOp",
    "WorkCentersListProductionRequestFilterItemValue",
    "WorkCentersListProductionRequestFilterItemValueThreeItem",
    "WorkCentersListProductionRequestSortItem",
    "WorkCentersListProductionRequestSortItemDir",
    "WorkCentersListProductionResponse",
    "WorkCentersListProductionResponseRowsItem",
    "WorkCentersUpdateProductionResponse",
]
