# This file was auto-generated by Fern from our API Definition.

import typing

from .maintenance_list_production_request_filter_item_value_three_item import (
    MaintenanceListProductionRequestFilterItemValueThreeItem,
)

MaintenanceListProductionRequestFilterItemValue = typing.Union[
    str, float, bool, typing.List[MaintenanceListProductionRequestFilterItemValueThreeItem]
]
