# This file was auto-generated by Fern from our API Definition.

import typing

from .post_v1production_routings_list_request_filter_item_value_three_item import (
    PostV1ProductionRoutingsListRequestFilterItemValueThreeItem,
)

PostV1ProductionRoutingsListRequestFilterItemValue = typing.Union[
    str, float, bool, typing.List[PostV1ProductionRoutingsListRequestFilterItemValueThreeItem]
]
