# This file was auto-generated by Fern from our API Definition.

import typing

from .work_centers_list_production_request_filter_item_value_three_item import (
    WorkCentersListProductionRequestFilterItemValueThreeItem,
)

WorkCentersListProductionRequestFilterItemValue = typing.Union[
    str, float, bool, typing.List[WorkCentersListProductionRequestFilterItemValueThreeItem]
]
