# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawAgreementsClient, RawAgreementsClient
from .types.post_v1agreements_agreements_create_request_items_item import (
    PostV1AgreementsAgreementsCreateRequestItemsItem,
)
from .types.post_v1agreements_agreements_create_request_status import PostV1AgreementsAgreementsCreateRequestStatus
from .types.post_v1agreements_agreements_create_response import PostV1AgreementsAgreementsCreateResponse
from .types.post_v1agreements_agreements_delete_response import PostV1AgreementsAgreementsDeleteResponse
from .types.post_v1agreements_agreements_get_response import PostV1AgreementsAgreementsGetResponse
from .types.post_v1agreements_agreements_list_request_filter_item import PostV1AgreementsAgreementsListRequestFilterItem
from .types.post_v1agreements_agreements_list_request_sort_item import PostV1AgreementsAgreementsListRequestSortItem
from .types.post_v1agreements_agreements_list_response import PostV1AgreementsAgreementsListResponse
from .types.post_v1agreements_agreements_update_request_status import PostV1AgreementsAgreementsUpdateRequestStatus
from .types.post_v1agreements_agreements_update_response import PostV1AgreementsAgreementsUpdateResponse
from .types.post_v1agreements_insurance_policies_create_response import PostV1AgreementsInsurancePoliciesCreateResponse
from .types.post_v1agreements_insurance_policies_delete_response import PostV1AgreementsInsurancePoliciesDeleteResponse
from .types.post_v1agreements_insurance_policies_list_request_filter_item import (
    PostV1AgreementsInsurancePoliciesListRequestFilterItem,
)
from .types.post_v1agreements_insurance_policies_list_request_sort_item import (
    PostV1AgreementsInsurancePoliciesListRequestSortItem,
)
from .types.post_v1agreements_insurance_policies_list_response import PostV1AgreementsInsurancePoliciesListResponse
from .types.post_v1agreements_types_create_response import PostV1AgreementsTypesCreateResponse
from .types.post_v1agreements_types_list_request_filter_item import PostV1AgreementsTypesListRequestFilterItem
from .types.post_v1agreements_types_list_request_sort_item import PostV1AgreementsTypesListRequestSortItem
from .types.post_v1agreements_types_list_response import PostV1AgreementsTypesListResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgreementsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgreementsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgreementsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgreementsClient
        """
        return self._raw_client

    def post_v1agreements_types_create(
        self, *, code: str, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1AgreementsTypesCreateResponse:
        """
        Parameters
        ----------
        code : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsTypesCreateResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.agreements.post_v1agreements_types_create(
            code="code",
            name="name",
        )
        """
        _response = self._raw_client.post_v1agreements_types_create(
            code=code, name=name, request_options=request_options
        )
        return _response.data

    def post_v1agreements_types_list(
        self,
        *,
        page: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        sort: typing.Optional[typing.Sequence[PostV1AgreementsTypesListRequestSortItem]] = OMIT,
        filter: typing.Optional[typing.Sequence[PostV1AgreementsTypesListRequestFilterItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1AgreementsTypesListResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[PostV1AgreementsTypesListRequestSortItem]]

        filter : typing.Optional[typing.Sequence[PostV1AgreementsTypesListRequestFilterItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsTypesListResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.agreements.post_v1agreements_types_list()
        """
        _response = self._raw_client.post_v1agreements_types_list(
            page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    def post_v1agreements_agreements_create(
        self,
        *,
        partner_id: str,
        number: str,
        start_date: str,
        type_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        end_date: typing.Optional[str] = OMIT,
        auto_renew: typing.Optional[bool] = OMIT,
        value: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        status: typing.Optional[PostV1AgreementsAgreementsCreateRequestStatus] = OMIT,
        notes: typing.Optional[str] = OMIT,
        items: typing.Optional[typing.Sequence[PostV1AgreementsAgreementsCreateRequestItemsItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1AgreementsAgreementsCreateResponse:
        """
        Parameters
        ----------
        partner_id : str

        number : str

        start_date : str

        type_id : typing.Optional[str]

        name : typing.Optional[str]

        end_date : typing.Optional[str]

        auto_renew : typing.Optional[bool]

        value : typing.Optional[str]

        currency : typing.Optional[str]

        status : typing.Optional[PostV1AgreementsAgreementsCreateRequestStatus]

        notes : typing.Optional[str]

        items : typing.Optional[typing.Sequence[PostV1AgreementsAgreementsCreateRequestItemsItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsAgreementsCreateResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.agreements.post_v1agreements_agreements_create(
            partner_id="partnerId",
            number="number",
            start_date="startDate",
        )
        """
        _response = self._raw_client.post_v1agreements_agreements_create(
            partner_id=partner_id,
            number=number,
            start_date=start_date,
            type_id=type_id,
            name=name,
            end_date=end_date,
            auto_renew=auto_renew,
            value=value,
            currency=currency,
            status=status,
            notes=notes,
            items=items,
            request_options=request_options,
        )
        return _response.data

    def post_v1agreements_agreements_get(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1AgreementsAgreementsGetResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsAgreementsGetResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.agreements.post_v1agreements_agreements_get(
            id="id",
        )
        """
        _response = self._raw_client.post_v1agreements_agreements_get(id=id, request_options=request_options)
        return _response.data

    def post_v1agreements_agreements_update(
        self,
        *,
        id: str,
        type_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        end_date: typing.Optional[str] = OMIT,
        auto_renew: typing.Optional[bool] = OMIT,
        value: typing.Optional[str] = OMIT,
        status: typing.Optional[PostV1AgreementsAgreementsUpdateRequestStatus] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1AgreementsAgreementsUpdateResponse:
        """
        Parameters
        ----------
        id : str

        type_id : typing.Optional[str]

        name : typing.Optional[str]

        end_date : typing.Optional[str]

        auto_renew : typing.Optional[bool]

        value : typing.Optional[str]

        status : typing.Optional[PostV1AgreementsAgreementsUpdateRequestStatus]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsAgreementsUpdateResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.agreements.post_v1agreements_agreements_update(
            id="id",
        )
        """
        _response = self._raw_client.post_v1agreements_agreements_update(
            id=id,
            type_id=type_id,
            name=name,
            end_date=end_date,
            auto_renew=auto_renew,
            value=value,
            status=status,
            notes=notes,
            request_options=request_options,
        )
        return _response.data

    def post_v1agreements_agreements_delete(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1AgreementsAgreementsDeleteResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsAgreementsDeleteResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.agreements.post_v1agreements_agreements_delete(
            id="id",
        )
        """
        _response = self._raw_client.post_v1agreements_agreements_delete(id=id, request_options=request_options)
        return _response.data

    def post_v1agreements_agreements_list(
        self,
        *,
        page: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        sort: typing.Optional[typing.Sequence[PostV1AgreementsAgreementsListRequestSortItem]] = OMIT,
        filter: typing.Optional[typing.Sequence[PostV1AgreementsAgreementsListRequestFilterItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1AgreementsAgreementsListResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[PostV1AgreementsAgreementsListRequestSortItem]]

        filter : typing.Optional[typing.Sequence[PostV1AgreementsAgreementsListRequestFilterItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsAgreementsListResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.agreements.post_v1agreements_agreements_list()
        """
        _response = self._raw_client.post_v1agreements_agreements_list(
            page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    def post_v1agreements_insurance_policies_create(
        self,
        *,
        policy_number: str,
        insured_object: str,
        from_date: str,
        to_date: str,
        insurer_partner_id: typing.Optional[str] = OMIT,
        premium: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1AgreementsInsurancePoliciesCreateResponse:
        """
        Parameters
        ----------
        policy_number : str

        insured_object : str

        from_date : str

        to_date : str

        insurer_partner_id : typing.Optional[str]

        premium : typing.Optional[str]

        currency : typing.Optional[str]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsInsurancePoliciesCreateResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.agreements.post_v1agreements_insurance_policies_create(
            policy_number="policyNumber",
            insured_object="insuredObject",
            from_date="fromDate",
            to_date="toDate",
        )
        """
        _response = self._raw_client.post_v1agreements_insurance_policies_create(
            policy_number=policy_number,
            insured_object=insured_object,
            from_date=from_date,
            to_date=to_date,
            insurer_partner_id=insurer_partner_id,
            premium=premium,
            currency=currency,
            notes=notes,
            request_options=request_options,
        )
        return _response.data

    def post_v1agreements_insurance_policies_list(
        self,
        *,
        page: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        sort: typing.Optional[typing.Sequence[PostV1AgreementsInsurancePoliciesListRequestSortItem]] = OMIT,
        filter: typing.Optional[typing.Sequence[PostV1AgreementsInsurancePoliciesListRequestFilterItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1AgreementsInsurancePoliciesListResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[PostV1AgreementsInsurancePoliciesListRequestSortItem]]

        filter : typing.Optional[typing.Sequence[PostV1AgreementsInsurancePoliciesListRequestFilterItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsInsurancePoliciesListResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.agreements.post_v1agreements_insurance_policies_list()
        """
        _response = self._raw_client.post_v1agreements_insurance_policies_list(
            page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    def post_v1agreements_insurance_policies_delete(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1AgreementsInsurancePoliciesDeleteResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsInsurancePoliciesDeleteResponse
            Default Response

        Examples
        --------
        from nordlet import Nordlet

        client = Nordlet(
            token="YOUR_TOKEN",
        )
        client.agreements.post_v1agreements_insurance_policies_delete(
            id="id",
        )
        """
        _response = self._raw_client.post_v1agreements_insurance_policies_delete(id=id, request_options=request_options)
        return _response.data


class AsyncAgreementsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgreementsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgreementsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgreementsClient
        """
        return self._raw_client

    async def post_v1agreements_types_create(
        self, *, code: str, name: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1AgreementsTypesCreateResponse:
        """
        Parameters
        ----------
        code : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsTypesCreateResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agreements.post_v1agreements_types_create(
                code="code",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1agreements_types_create(
            code=code, name=name, request_options=request_options
        )
        return _response.data

    async def post_v1agreements_types_list(
        self,
        *,
        page: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        sort: typing.Optional[typing.Sequence[PostV1AgreementsTypesListRequestSortItem]] = OMIT,
        filter: typing.Optional[typing.Sequence[PostV1AgreementsTypesListRequestFilterItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1AgreementsTypesListResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[PostV1AgreementsTypesListRequestSortItem]]

        filter : typing.Optional[typing.Sequence[PostV1AgreementsTypesListRequestFilterItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsTypesListResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agreements.post_v1agreements_types_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1agreements_types_list(
            page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    async def post_v1agreements_agreements_create(
        self,
        *,
        partner_id: str,
        number: str,
        start_date: str,
        type_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        end_date: typing.Optional[str] = OMIT,
        auto_renew: typing.Optional[bool] = OMIT,
        value: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        status: typing.Optional[PostV1AgreementsAgreementsCreateRequestStatus] = OMIT,
        notes: typing.Optional[str] = OMIT,
        items: typing.Optional[typing.Sequence[PostV1AgreementsAgreementsCreateRequestItemsItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1AgreementsAgreementsCreateResponse:
        """
        Parameters
        ----------
        partner_id : str

        number : str

        start_date : str

        type_id : typing.Optional[str]

        name : typing.Optional[str]

        end_date : typing.Optional[str]

        auto_renew : typing.Optional[bool]

        value : typing.Optional[str]

        currency : typing.Optional[str]

        status : typing.Optional[PostV1AgreementsAgreementsCreateRequestStatus]

        notes : typing.Optional[str]

        items : typing.Optional[typing.Sequence[PostV1AgreementsAgreementsCreateRequestItemsItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsAgreementsCreateResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agreements.post_v1agreements_agreements_create(
                partner_id="partnerId",
                number="number",
                start_date="startDate",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1agreements_agreements_create(
            partner_id=partner_id,
            number=number,
            start_date=start_date,
            type_id=type_id,
            name=name,
            end_date=end_date,
            auto_renew=auto_renew,
            value=value,
            currency=currency,
            status=status,
            notes=notes,
            items=items,
            request_options=request_options,
        )
        return _response.data

    async def post_v1agreements_agreements_get(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1AgreementsAgreementsGetResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsAgreementsGetResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agreements.post_v1agreements_agreements_get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1agreements_agreements_get(id=id, request_options=request_options)
        return _response.data

    async def post_v1agreements_agreements_update(
        self,
        *,
        id: str,
        type_id: typing.Optional[str] = OMIT,
        name: typing.Optional[str] = OMIT,
        end_date: typing.Optional[str] = OMIT,
        auto_renew: typing.Optional[bool] = OMIT,
        value: typing.Optional[str] = OMIT,
        status: typing.Optional[PostV1AgreementsAgreementsUpdateRequestStatus] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1AgreementsAgreementsUpdateResponse:
        """
        Parameters
        ----------
        id : str

        type_id : typing.Optional[str]

        name : typing.Optional[str]

        end_date : typing.Optional[str]

        auto_renew : typing.Optional[bool]

        value : typing.Optional[str]

        status : typing.Optional[PostV1AgreementsAgreementsUpdateRequestStatus]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsAgreementsUpdateResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agreements.post_v1agreements_agreements_update(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1agreements_agreements_update(
            id=id,
            type_id=type_id,
            name=name,
            end_date=end_date,
            auto_renew=auto_renew,
            value=value,
            status=status,
            notes=notes,
            request_options=request_options,
        )
        return _response.data

    async def post_v1agreements_agreements_delete(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1AgreementsAgreementsDeleteResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsAgreementsDeleteResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agreements.post_v1agreements_agreements_delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1agreements_agreements_delete(id=id, request_options=request_options)
        return _response.data

    async def post_v1agreements_agreements_list(
        self,
        *,
        page: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        sort: typing.Optional[typing.Sequence[PostV1AgreementsAgreementsListRequestSortItem]] = OMIT,
        filter: typing.Optional[typing.Sequence[PostV1AgreementsAgreementsListRequestFilterItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1AgreementsAgreementsListResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[PostV1AgreementsAgreementsListRequestSortItem]]

        filter : typing.Optional[typing.Sequence[PostV1AgreementsAgreementsListRequestFilterItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsAgreementsListResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agreements.post_v1agreements_agreements_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1agreements_agreements_list(
            page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    async def post_v1agreements_insurance_policies_create(
        self,
        *,
        policy_number: str,
        insured_object: str,
        from_date: str,
        to_date: str,
        insurer_partner_id: typing.Optional[str] = OMIT,
        premium: typing.Optional[str] = OMIT,
        currency: typing.Optional[str] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1AgreementsInsurancePoliciesCreateResponse:
        """
        Parameters
        ----------
        policy_number : str

        insured_object : str

        from_date : str

        to_date : str

        insurer_partner_id : typing.Optional[str]

        premium : typing.Optional[str]

        currency : typing.Optional[str]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsInsurancePoliciesCreateResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agreements.post_v1agreements_insurance_policies_create(
                policy_number="policyNumber",
                insured_object="insuredObject",
                from_date="fromDate",
                to_date="toDate",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1agreements_insurance_policies_create(
            policy_number=policy_number,
            insured_object=insured_object,
            from_date=from_date,
            to_date=to_date,
            insurer_partner_id=insurer_partner_id,
            premium=premium,
            currency=currency,
            notes=notes,
            request_options=request_options,
        )
        return _response.data

    async def post_v1agreements_insurance_policies_list(
        self,
        *,
        page: typing.Optional[int] = OMIT,
        page_size: typing.Optional[int] = OMIT,
        sort: typing.Optional[typing.Sequence[PostV1AgreementsInsurancePoliciesListRequestSortItem]] = OMIT,
        filter: typing.Optional[typing.Sequence[PostV1AgreementsInsurancePoliciesListRequestFilterItem]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PostV1AgreementsInsurancePoliciesListResponse:
        """
        Parameters
        ----------
        page : typing.Optional[int]

        page_size : typing.Optional[int]

        sort : typing.Optional[typing.Sequence[PostV1AgreementsInsurancePoliciesListRequestSortItem]]

        filter : typing.Optional[typing.Sequence[PostV1AgreementsInsurancePoliciesListRequestFilterItem]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsInsurancePoliciesListResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agreements.post_v1agreements_insurance_policies_list()


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1agreements_insurance_policies_list(
            page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    async def post_v1agreements_insurance_policies_delete(
        self, *, id: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostV1AgreementsInsurancePoliciesDeleteResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostV1AgreementsInsurancePoliciesDeleteResponse
            Default Response

        Examples
        --------
        import asyncio

        from nordlet import AsyncNordlet

        client = AsyncNordlet(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agreements.post_v1agreements_insurance_policies_delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_v1agreements_insurance_policies_delete(
            id=id, request_options=request_options
        )
        return _response.data
